
; ---------------------------------------------------------------

        z80prog	0


; enum FMChannelStruct
id:		 equ 0
duration:	 equ 22h
volume:		 equ 23h
octave:		 equ 24h
voice:		 equ 41h
algorithm:	 equ 42h
fm3_op:		 equ 45h
note_on:	 equ 46h
note_off:	 equ 47h

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: B3-432E-F558-21			    |
; |				Ilfak Guilfanov				    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	5C6B6E6FE72C10EE90F6E4C07151968B
; Input	CRC32 :	8DC974D0

; ---------------------------------------------------------------------------
; File Name   :	D:\Sega\Dev\Disasms\Verytex\Z80Driver.bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 1C00h Loaded length: 1C00h

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Pure code

loc_0:						    ; DATA XREF: ROM:off_1033o
		di

loc_1:
		im	2
		jp	loc_100
; ---------------------------------------------------------------------------
		align 100h
; ---------------------------------------------------------------------------

loc_100:					    ; CODE XREF: ROM:0003j
		di
		jp	InitDriver
; ---------------------------------------------------------------------------
byte_104:	db 0				    ; DATA XREF: ROM:loc_324r
						    ; ROM:0352r ...
ROMBank:	dw 0				    ; DATA XREF: ROM:0C2Er
						    ; ROM:LoadBGMFromROMr
BGMNum:		db 0				    ; DATA XREF: ROM:03CBr
						    ; ROM:loc_3D3w ...
InputCmd:	db 0				    ; DATA XREF: ROM:0345w
						    ; ROM:035Dw ...
BGMPlaying:	db 0				    ; DATA XREF: ROM:033Cr
						    ; ROM:loc_34Cr ...
byte_10A:	db 0				    ; DATA XREF: ROM:041Cw
						    ; ROM:loc_1604o
byte_10B:	db 0				    ; DATA XREF: ROM:162Dr
						    ; ROM:loc_1633o
byte_10C:	db 0				    ; DATA XREF: ROM:0439r
						    ; ROM:0440w ...
u_68kTrueStory:	db 0				    ; DATA XREF: ROM:0C23w
						    ; StopBGM+20w
u_CmdTbl:	dw loc_556			    ; DATA XREF: UpdateSounds:loc_506r
						    ; default routine
		dw FadeOutBGM
		dw PlayBGM
		dw StopBGM2
		dw loc_52D
		dw loc_541
VolumeTable:	db  5Fh, 2Ah, 28h, 25h,	22h, 20h    ; DATA XREF: ROM:0A52o
		db  1Dh, 1Ah, 18h, 15h,	12h, 10h
		db  0Dh, 0Ah,	8,   5,	  2,   0
off_12C:	dw loc_16DF			    ; DATA XREF: ROM:loc_16B1r
		dw loc_1708
		dw loc_1723
		dw loc_175A
		dw loc_1769
		dw loc_1778
		dw loc_1780
		dw loc_1791
OverrideTable:	db    0,   0,	0,   0,	  0	    ; DATA XREF: ROM:0656o
						    ; ROM:165Fo
		db    0,   0,	0,   0,	  0
		db    0
		db    0
off_148:	dw loc_690			    ; DATA XREF: ROM:loc_67Dr
						    ; FM
		dw loc_681			    ; PSG1--PSG3
		dw loc_690			    ; PSG4
		dw 0
		dw 0
NoteCmdTable:	dw LoadNote			    ; DATA XREF: ROM:loc_6D7r
						    ; FM
		dw LoadPSGNote			    ; PSG1-PSG3
		dw LoadPSGNoiseNote		    ; PSG4
		dw 0
		dw 0
off_15C:	dw loc_783			    ; DATA XREF: ROM:loc_77Fr
		dw loc_78C
		dw loc_795
		dw loc_79A
VolCmdTable:	dw UpdateVolume			    ; DATA XREF: ROM:loc_A46r
						    ; FM
		dw locret_A7E			    ; PSG1--PSG3
		dw locret_A7E			    ; PSG4
		dw 0
		dw 0
TLTransferCnt:	db    1,   1,	1,   1,	  2,   3,   3,	 4; 0 ;	DATA XREF: ROM:loc_A5Fr
FlagsTable:	dw Flag00_AlterTempo		    ; 0	; DATA XREF: ROM:loc_6CAr
		dw Flag01_LoadFMVoice		    ; 1
		dw Flag02_LoadPSGVoice		    ; 2
		dw Flag03_SetVolume		    ; 3
		dw Flag04_VolumeUp		    ; 4
		dw Flag05_VolumeDown		    ; 5
		dw Flag06_AlterVolume		    ; 6
		dw Flag07_SetOctave		    ; 7
		dw Flag08_NextOctave		    ; 8
		dw Flag09_PrevOctave		    ; 9
		dw Flag0A_AlterOctave		    ; 0Ah
		dw Flag0B_u_Set22h		    ; 0Bh
		dw Flag0C_u_Set28h		    ; 0Ch
		dw Flag0D_SendYMCommand		    ; 0Dh
		dw Flag0E_SetRepeat		    ; 0Eh
		dw Flag0F_Repeat		    ; 0Fh
		dw Flag10_StopRepeat		    ; 10h
		dw Flag11			    ; 11h
		dw Flag12_JumpTo		    ; 12h
		dw Flag13_Call			    ; 13h
		dw Flag14_Return		    ; 14h
		dw Flag15			    ; 15h
		dw Flag16_AlterFrequency	    ; 16h
		dw Flag17			    ; 17h
		dw Flag18_SetSpecFM3		    ; 18h
		dw Flag19_ResetSpecFM3		    ; 19h
		dw Flag1A_PanLR			    ; 1Ah
		dw Flag1B_PanLeft		    ; 1Bh
		dw Flag1C_PanRight		    ; 1Ch
		dw Flag1D			    ; 1Dh
FMFrequencies:	dw   284h,  2ABh,  2D3h,  2FEh,	 32Dh,	35Ch,  38Fh,  3C5h,  3FFh,  43Ch,  47Ch,  4C0h;	0
						    ; DATA XREF: ROM:0CEDt
						    ; ROM:0CF6t ...
		dw  0A84h, 0AABh, 0AD3h, 0AFEh,	0B2Dh, 0B5Ch, 0B8Fh, 0BC5h, 0BFFh, 0C3Ch, 0C7Ch, 0CC0h;	12
		dw  1284h, 12ABh, 12D3h, 12FEh,	132Dh, 135Ch, 138Fh, 13C5h, 13FFh, 143Ch, 147Ch, 14C0h;	24
		dw  1A84h, 1AABh, 1AD3h, 1AFEh,	1B2Dh, 1B5Ch, 1B8Fh, 1BC5h, 1BFFh, 1C3Ch, 1C7Ch, 1CC0h;	36
		dw  2284h, 22ABh, 22D3h, 22FEh,	232Dh, 235Ch, 238Fh, 23C5h, 23FFh, 243Ch, 247Ch, 24C0h;	48
		dw  2A84h, 2AABh, 2AD3h, 2AFEh,	2B2Dh, 2B5Ch, 2B8Fh, 2BC5h, 2BFFh, 2C3Ch, 2C7Ch, 2CC0h;	60
		dw  3284h, 32ABh, 32D3h, 32FEh,	332Dh, 335Ch, 338Fh, 33C5h, 33FFh, 343Ch, 347Ch, 34C0h;	72
		dw  3A84h, 3AABh, 3AD3h, 3AFEh,	3B2Dh, 3B5Ch, 3B8Fh, 3BC5h, 3BFFh, 3C3Ch, 3C7Ch, 3CC0h;	84
		db  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0;, 0, 0
PSGFrequencies:	dw   3F7h,  3BEh,  388h,  356h,	 326h,	2F9h,  2CEh,  2A5h,  280h,  25Ch,  23Ah,  21Ah;	0
		dw   1FBh,  1DFh,  1C4h,  1ABh,	 193h,	17Dh,  167h,  153h,  140h,  12Eh,  11Dh,  10Dh;	12
		dw   0FEh,  0EFh,  0E2h,  0D6h,	 0C9h,	0BEh,  0B4h,  0A9h,  0A0h,   97h,   8Fh,   87h;	24
		dw    7Fh,   78h,   71h,   6Bh,	  65h,	 5Fh,	5Ah,   55h,   50h,   4Bh,   47h,   43h;	36
		dw    40h,   3Ch,   39h,   36h,	  33h,	 30h,	2Dh,   2Bh,   28h,   26h,   24h,   22h;	48
		dw    20h,   1Fh,   1Dh,   1Bh,	  1Ah,	 18h,	17h,   16h,   15h,   13h,   12h,   11h;	60
		dw    10h,   0Fh,   0Eh		    ; 72
; ---------------------------------------------------------------------------

InitDriver:					    ; CODE XREF: ROM:0101j
		di
		im	2
		ld	hl, 2000h
		ld	sp, hl
		call	InitSoundChips

loc_324:					    ; CODE XREF: ROM:04A9j
						    ; ROM:04AFj
		ld	a, (byte_104)
		zand	60h
		cp	60h
		jr	nz, loc_334
		ld	a, 0FFh
		ld	(byte_4B7), a
		jr	loc_34C
; ---------------------------------------------------------------------------

loc_334:					    ; CODE XREF: ROM:032Bj
		ld	a, (byte_4B7)
		zor	a
		jr	z, loc_34C
		ld	b, 4
		ld	a, (BGMPlaying)
		cp	0FFh
		jr	nz, loc_344
		inc	b

loc_344:					    ; CODE XREF: ROM:0341j
		ld	a, b
		ld	(InputCmd), a
		xor	a
		ld	(byte_4B7), a

loc_34C:					    ; CODE XREF: ROM:0332j
						    ; ROM:0338j
		ld	a, (BGMPlaying)
		zor	a
		jr	z, loc_360
		ld	a, (byte_104)
		xor	0FFh
		zand	30h
		jr	nz, loc_360
		ld	a, 1
		ld	(InputCmd), a

loc_360:					    ; CODE XREF: ROM:0350j
						    ; ROM:0359j
		ld	a, (BGMPlaying)
		zor	a
		jr	nz, loc_387
		ld	a, (byte_104)
		xor	0FFh
		zand	30h
		cp	20h
		jr	nz, loc_378
		ld	a, 0FFh
		ld	(byte_4B2), a
		jr	loc_387
; ---------------------------------------------------------------------------

loc_378:					    ; CODE XREF: ROM:036Fj
		ld	a, (byte_4B2)
		zor	a
		jr	z, loc_387
		ld	a, 2
		ld	(InputCmd), a
		xor	a
		ld	(byte_4B2), a

loc_387:					    ; CODE XREF: ROM:0364j
						    ; ROM:0376j ...
		ld	a, (BGMPlaying)
		zor	a
		jr	z, loc_3AE
		ld	a, (byte_104)
		xor	0FFh
		zand	30h
		cp	20h
		jr	nz, loc_39F
		ld	a, 0FFh
		ld	(byte_4B3), a
		jr	loc_3AE
; ---------------------------------------------------------------------------

loc_39F:					    ; CODE XREF: ROM:0396j
		ld	a, (byte_4B3)
		zor	a
		jr	z, loc_3AE
		ld	a, 3
		ld	(InputCmd), a
		xor	a
		ld	(byte_4B3), a

loc_3AE:					    ; CODE XREF: ROM:038Bj
						    ; ROM:039Dj ...
		ld	a, (byte_104)
		xor	0FFh
		zand	8
		jr	nz, loc_3BE
		ld	a, 0FFh
		ld	(byte_4B4), a
		jr	loc_3D6
; ---------------------------------------------------------------------------

loc_3BE:					    ; CODE XREF: ROM:03B5j
		ld	a, (byte_4B4)
		zor	a
		jr	z, loc_3D6
		xor	a
		ld	(byte_4B4), a
		ld	hl, 8000h
		ld	a, (BGMNum)
		inc	a
		cp	(hl)
		jr	nz, loc_3D3
		xor	a

loc_3D3:					    ; CODE XREF: ROM:03D0j
		ld	(BGMNum), a

loc_3D6:					    ; CODE XREF: ROM:03BCj
						    ; ROM:03C2j
		ld	a, (byte_104)
		xor	0FFh
		zand	4
		jr	nz, loc_3E7
		ld	a, 0FFh
		ld	(byte_4B5), a
		jp	loc_401
; ---------------------------------------------------------------------------

loc_3E7:					    ; CODE XREF: ROM:03DDj
		ld	a, (byte_4B5)
		zor	a
		jp	z, loc_401
		xor	a
		ld	(byte_4B5), a
		ld	a, (BGMNum)
		dec	a
		cp	0FFh
		jr	nz, loc_3FE
		ld	a, (8000h)
		dec	a

loc_3FE:					    ; CODE XREF: ROM:03F8j
		ld	(BGMNum), a

loc_401:					    ; CODE XREF: ROM:03E4j
						    ; ROM:03EBj
		ld	a, (byte_104)
		xor	0FFh
		zand	0A0h
		cp	20h
		jr	nz, loc_413
		ld	a, 0FFh
		ld	(byte_4B8), a
		jr	loc_423
; ---------------------------------------------------------------------------

loc_413:					    ; CODE XREF: ROM:040Aj
		ld	a, (byte_4B8)
		zor	a
		jr	z, loc_423
		ld	a, (byte_4BC)
		ld	(byte_10A), a
		xor	a
		ld	(byte_4B8), a

loc_423:					    ; CODE XREF: ROM:0411j
						    ; ROM:0417j
		ld	a, (byte_104)
		xor	0FFh
		zand	0A0h
		jr	nz, loc_433
		ld	a, 0FFh
		ld	(byte_4B9), a
		jr	loc_452
; ---------------------------------------------------------------------------

loc_433:					    ; CODE XREF: ROM:042Aj
		ld	a, (byte_4B9)
		zor	a
		jr	z, loc_452
		ld	a, (byte_10C)
		zor	a
		jr	z, loc_448
		xor	a
		ld	(byte_10C), a
		ld	(byte_4B9), a
		jr	loc_452
; ---------------------------------------------------------------------------

loc_448:					    ; CODE XREF: ROM:043Dj
		ld	a, (byte_4BC)
		ld	(byte_10C), a
		xor	a
		ld	(byte_4B9), a

loc_452:					    ; CODE XREF: ROM:0431j
						    ; ROM:0437j ...
		ld	a, (byte_104)
		xor	0FFh
		zand	1
		jr	nz, loc_463
		ld	a, 0FFh
		ld	(byte_4BA), a
		jp	loc_47B
; ---------------------------------------------------------------------------

loc_463:					    ; CODE XREF: ROM:0459j
		ld	a, (byte_4BA)
		zor	a
		jp	z, loc_47B
		xor	a
		ld	(byte_4BA), a
		ld	a, (byte_4BC)
		inc	a
		cp	39h
		jr	nz, loc_478
		ld	a, 20h

loc_478:					    ; CODE XREF: ROM:0474j
		ld	(byte_4BC), a

loc_47B:					    ; CODE XREF: ROM:0460j
						    ; ROM:0467j
		ld	a, (byte_104)
		xor	0FFh
		zand	2
		jr	nz, loc_48C
		ld	a, 0FFh
		ld	(byte_4BB), a
		jp	loc_4A4
; ---------------------------------------------------------------------------

loc_48C:					    ; CODE XREF: ROM:0482j
		ld	a, (byte_4BB)
		zor	a
		jp	z, loc_4A4
		xor	a
		ld	(byte_4BB), a
		ld	a, (byte_4BC)
		dec	a
		cp	1Fh
		jr	nz, loc_4A1
		ld	a, 38h

loc_4A1:					    ; CODE XREF: ROM:049Dj
		ld	(byte_4BC), a

loc_4A4:					    ; CODE XREF: ROM:0489j
						    ; ROM:0490j
		call	GetYMState
		zand	3			    ; test for YM timer	overflow
		jp	z, loc_324		    ; if no overflow, branch
		call	UpdateSounds
		jp	loc_324
; ---------------------------------------------------------------------------
byte_4B2:	db 0				    ; DATA XREF: ROM:0373w
						    ; ROM:loc_378r ...
byte_4B3:	db 0				    ; DATA XREF: ROM:039Aw
						    ; ROM:loc_39Fr ...
byte_4B4:	db 0				    ; DATA XREF: ROM:03B9w
						    ; ROM:loc_3BEr ...
byte_4B5:	db 0				    ; DATA XREF: ROM:03E1w
						    ; ROM:loc_3E7r ...
		db    0
byte_4B7:	db 0				    ; DATA XREF: ROM:032Fw
						    ; ROM:loc_334r ...
byte_4B8:	db 0				    ; DATA XREF: ROM:040Ew
						    ; ROM:loc_413r ...
byte_4B9:	db 0				    ; DATA XREF: ROM:042Ew
						    ; ROM:loc_433r ...
byte_4BA:	db 0				    ; DATA XREF: ROM:045Dw
						    ; ROM:loc_463r ...
byte_4BB:	db 0				    ; DATA XREF: ROM:0486w
						    ; ROM:loc_48Cr ...
byte_4BC:	db 20h				    ; DATA XREF: ROM:0419r
						    ; ROM:loc_448r ...
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    6
		db    2
		db    0
		db    6
		db    4
		db    0
		db    6
		db    8
		db    0
		db    6
		db  10h
		db    0
		db    6
		db  20h
		db    0
		db    6
		db  40h	; @
		db    0
		db    6
		db  80h	; Ä
		db    0
		db    7
		db    1
		db    0
		db    7
		db    2
		db    0
		db    6
		db    1
		db    0
		db    5
		db  80h	; Ä
		db    0
		db    5
		db  40h	; @
		db    0

; =============== S U B	R O U T	I N E =======================================


UpdateSounds:					    ; CODE XREF: ROM:04ACp
		ld	a, (InputCmd)
		cp	6
		jr	nc, InputDone
		zadd	a, a
		zadd	a, 0Eh
		ld	(loc_506+1), a

loc_506:					    ; DATA XREF: UpdateSounds+Aw
		ld	hl, (u_CmdTbl)
		jp	(hl)
; ---------------------------------------------------------------------------

FadeOutBGM:					    ; DATA XREF: ROM:0110o
		ld	a, (u_FadeOutCnt)
		zor	a
		jr	nz, InputDone
		ld	a, 1
		ld	(u_FadeOutCnt),	a
		ld	a, 18h
		ld	(u_BGMUpdCounter), a
		jr	InputDone
; ---------------------------------------------------------------------------

PlayBGM:					    ; DATA XREF: ROM:0112o
		ld	a, (BGMPlaying)
		zor	a
		call	nz, StopBGM
		call	LoadBGMFromROM
		jr	InputDone
; ---------------------------------------------------------------------------

StopBGM2:					    ; DATA XREF: ROM:0114o
		call	StopBGM
		jr	InputDone
; ---------------------------------------------------------------------------

loc_52D:					    ; DATA XREF: ROM:0116o
		ld	a, (BGMPlaying)
		cp	0FFh
		jr	z, InputDone
		zor	a
		jr	z, InputDone
		ld	a, 0FFh
		ld	(BGMPlaying), a
		call	sub_5BD
		jr	InputDone
; ---------------------------------------------------------------------------

loc_541:					    ; DATA XREF: ROM:0118o
		ld	a, (BGMPlaying)
		cp	0FFh
		jr	nz, InputDone
		call	sub_5CB
		ld	a, 1
		ld	(BGMPlaying), a
		jr	InputDone

InputDone:					    ; CODE XREF: UpdateSounds+5j
						    ; UpdateSounds+15j	...
		xor	a
		ld	(InputCmd), a

loc_556:					    ; DATA XREF: ROM:u_CmdTblo
		call	GetYMState
		zand	2
		jr	z, loc_576
		ld	a, (BGMPlaying)		    ; is BGM playing?
		cp	0FFh
		jr	z, loc_567		    ; if not, branch
		call	UpdateBGM		    ; otherwise, update	it

loc_567:					    ; CODE XREF: UpdateSounds+69j
		ld	bc, 272Fh		    ; timers + CH3 mode
		ld	a, (Struct_FM3+45h)
		rrc	a
		rrc	a
		zor	c
		ld	c, a
		call	WriteYM_Port0

loc_576:					    ; CODE XREF: UpdateSounds+62j
		call	GetYMState
		zand	1
		ret	z
		ld	a, (BGMPlaying)		    ; is BGM playing?
		cp	0FFh
		jr	z, loc_586		    ; if not, branch
		call	loc_1604

loc_586:					    ; CODE XREF: UpdateSounds+88j
		ld	bc, 271Fh
		ld	a, (Struct_FM3+45h)
		rrc	a
		rrc	a
		zor	c
		ld	c, a
		call	WriteYM_Port0
		ret
; End of function UpdateSounds


; =============== S U B	R O U T	I N E =======================================


InitSoundChips:					    ; CODE XREF: ROM:0321p
		call	StopBGM
		ld	bc, 2983h
		call	WriteYM_Port0
		ld	bc, 272Fh
		call	WriteYM_Port0
		ld	bc, 2500h
		call	WriteYM_Port0
		ld	bc, 24AEh
		call	WriteYM_Port0
		ld	bc, 271Fh
		call	WriteYM_Port0
		ld	a, 0FFh
		ld	(7F11h), a
		ret
; End of function InitSoundChips


; =============== S U B	R O U T	I N E =======================================


sub_5BD:					    ; CODE XREF: UpdateSounds+43p
		ld	a, 0
		ld	(byte_61D), a
		call	u_FadeOutBGMLoop
		ld	a, 0FFh
		ld	(7F11h), a
		ret
; End of function sub_5BD


; =============== S U B	R O U T	I N E =======================================


sub_5CB:					    ; CODE XREF: UpdateSounds+4Fp
		ld	a, 1
		ld	(byte_61D), a
		call	u_FadeOutBGMLoop
		ret
; End of function sub_5CB


; =============== S U B	R O U T	I N E =======================================


u_FadeOutBGMLoop:				    ; CODE XREF: sub_5BD+5p
						    ; sub_5CB+5p
		ld	a, 0Ah
		ld	(BGM_CurrentChannel), a
		ld	hl, ChannelPointers

loc_5DC:					    ; CODE XREF: u_FadeOutBGMLoop+46j
		call	LoadChannel
		ex	de, hl
		ld	a, (ix+0)
		cp	7
		call	z, SetYM_Port1
		ld	a, (iy+0)		    ; load channel type
		zor	a
		jr	nz, loc_5FB		    ; if this is PSG channel, branch
		ld	a, (byte_61D)
		ld	c, a
		zor	a
		jr	z, loc_5F8
		ld	c, (ix+volume)

loc_5F8:					    ; CODE XREF: u_FadeOutBGMLoop+1Fj
		call	UpdateVolume

loc_5FB:					    ; CODE XREF: u_FadeOutBGMLoop+18j
		ld	a, (iy+0)		    ; load channel type
		dec	a			    ; is this PSG1--PSG3?
		jr	nz, loc_60D		    ; if not, branch
		ld	a, (byte_61D)
		zor	a
		jr	z, loc_60A
		ld	a, (ix+2Bh)

loc_60A:					    ; CODE XREF: u_FadeOutBGMLoop+31j
		call	u_WritePSG

loc_60D:					    ; CODE XREF: u_FadeOutBGMLoop+2Bj
		ld	a, (ix+0)
		cp	9			    ; is this the last channel to process?
		call	z, SetYM_Port0		    ; if yes, call
		ld	hl, BGM_CurrentChannel
		dec	(hl)			    ; do we have channels to update?
		ex	de, hl
		jr	nz, loc_5DC		    ; if yes, branch
		ret
; End of function u_FadeOutBGMLoop

; ---------------------------------------------------------------------------
byte_61D:	db 0				    ; DATA XREF: sub_5BD+2w
						    ; sub_5CB+2w ...
; ---------------------------------------------------------------------------

UpdateBGM:					    ; CODE XREF: UpdateSounds+6Bp
						    ; ROM:082Aj ...
		ld	a, 0Ah
		ld	(BGM_CurrentChannel), a	    ; set number of channels to	10
		ld	hl, ChannelPointers
		ld	(ChannelOffset), hl	    ; set channel struct pointers
		ld	a, (u_FadeOutCnt)
		zor	a
		jr	z, UpdateBGM_ProcessChannel
		ld	hl, u_BGMUpdCounter
		dec	(hl)
		jr	nz, UpdateBGM_ProcessChannel
		ld	(hl), 18h
		inc	a
		cp	0Eh
		jp	z, StopBGM
		ld	(u_FadeOutCnt),	a

UpdateBGM_ProcessChannel:			    ; CODE XREF: ROM:062Dj
						    ; ROM:0633j ...
		ld	hl, (ChannelOffset)
		call	LoadChannel
		ld	(ChannelOffset), hl
		ld	a, (ix+0)
		cp	7
		call	z, SetYM_Port1		    ; set YM port 1 for	FM3--FM6
		ld	b, 0
		ld	c, (ix+0)		    ; bc = Channel id
		ld	hl, OverrideTable
		zadd	hl, bc
		ld	a, (hl)
		zor	a			    ; is this channel being overriden?
		jr	z, loc_690		    ; if not, branch
		zand	0FEh
		jr	nz, loc_672
		ld	a, 0C9h			    ; a	= ret
		ld	(WriteYM_AutoPort_Safe), a
		ld	(WriteYM_Port0_Safe), a
		ld	(u_WritePSG_Safe), a
		ld	(u_WritePSG2_Safe), a
		jr	loc_690
; ---------------------------------------------------------------------------

loc_672:					    ; CODE XREF: ROM:0660j
		ld	(hl), 0
		ld	a, (iy+0)		    ; load channel type
		zadd	a, a
		zadd	a, 48h
		ld	(loc_67D+1), a

loc_67D:					    ; DATA XREF: ROM:067Aw
		ld	hl, (off_148)
		jp	(hl)
; ---------------------------------------------------------------------------

loc_681:					    ; DATA XREF: ROM:014Ao
		ld	l, (ix+29h)
		ld	h, (ix+2Ah)
		call	u_WritePSG2
		ld	a, (ix+2Bh)
		call	u_WritePSG

loc_690:					    ; CODE XREF: ROM:065Cj
						    ; ROM:0670j
						    ; DATA XREF: ...
		ld	a, (iy+0)		    ; load channel type
		dec	a			    ; is this PSG channel?
		jr	z, loc_6A9		    ; if yes, branch
		ld	a, (u_FadeOutCnt)
		zor	a
		jr	z, loc_6A9
		ld	a, (u_BGMUpdCounter)
		dec	a
		cp	(ix+0)
		ld	a, (ix+volume)
		call	z, SetVolume2

loc_6A9:					    ; CODE XREF: ROM:0694j
						    ; ROM:069Aj
		dec	(ix+2)			    ; decrease note duration
		jp	nz, Track_NoteLasts	    ; if durations remains, branch
		ld	e, (ix+3)
		ld	d, (ix+4)		    ; de = Current position in track

RunBGMTrack:					    ; CODE XREF: ROM:0869j
						    ; DATA XREF: ROM:06C0o
		ld	a, (de)
		cp	0FFh			    ; byte 0FFh	is met?
		jp	z, StopBGM		    ; if so, stop BGM???
		bit	7, a
		jr	nz, Track_GotNote
		inc	de
		ld	hl, RunBGMTrack
		push	hl			    ; repeat this routine after	conditional flag is done
		zadd	a, a
		zadd	a, 76h
		ld	(loc_6CA+1), a

loc_6CA:					    ; DATA XREF: ROM:06C7w
		ld	hl, (FlagsTable)
		jp	(hl)
; ---------------------------------------------------------------------------

Track_GotNote:					    ; CODE XREF: ROM:06BDj
		ld	a, (iy+0)		    ; load channel type
		zadd	a, a
		zadd	a, 52h
		ld	(loc_6D7+1), a

loc_6D7:					    ; DATA XREF: ROM:06D4w
		ld	hl, (NoteCmdTable)
		jp	(hl)
; ---------------------------------------------------------------------------

Track_NoteLasts:				    ; CODE XREF: ROM:06ACj
						    ; ROM:088Dj ...
		ld	a, (iy+0)
		cp	2			    ; is this PSG4?
		jp	nc, NoteLasts_PSG_or_FM	    ; if not, branch
		bit	4, (ix+1)
		jr	nz, loc_704
		ld	a, (ix+2)
		cp	(ix+28h)
		jr	nz, loc_704
		ld	a, (iy+0)
		zor	a
		jr	nz, loc_701
		ld	b, 28h			    ; YM note on/off register
		ld	c, (ix+note_off)
		call	WriteYM_Port0_Safe
		jr	loc_704
; ---------------------------------------------------------------------------

loc_701:					    ; CODE XREF: ROM:06F5j
		call	sub_994

loc_704:					    ; CODE XREF: ROM:06E7j
						    ; ROM:06EFj ...
		xor	a
		ld	(SavedNote), a
		ld	a, (ix+2Eh)
		zor	a
		jr	z, loc_755
		ld	a, (ix+37h)
		zor	a
		jr	z, loc_719
		dec	(ix+37h)
		jr	loc_755
; ---------------------------------------------------------------------------

loc_719:					    ; CODE XREF: ROM:0712j
		dec	(ix+33h)
		jr	nz, loc_755
		ld	a, (ix+2Eh)
		ld	(ix+33h), a
		ld	(SavedNote), a
		ld	l, (ix+2Ch)
		ld	h, (ix+2Dh)
		ld	e, (ix+34h)
		ld	d, (ix+35h)
		zadd	hl, de
		ld	(ix+2Ch), l
		ld	(ix+2Dh), h
		dec	(ix+36h)
		jr	nz, loc_755
		ld	a, (ix+31h)
		zadd	a, a
		ld	(ix+36h), a
		ld	a, (ix+35h)
		cpl
		ld	(ix+35h), a
		ld	a, (ix+34h)
		zneg
		ld	(ix+34h), a

loc_755:					    ; CODE XREF: ROM:070Cj
						    ; ROM:0717j ...
		bit	0, (ix+38h)
		jr	z, loc_7B7
		ld	a, (ix+40h)
		zor	a
		jr	z, loc_766
		dec	(ix+40h)
		jr	loc_7B7
; ---------------------------------------------------------------------------

loc_766:					    ; CODE XREF: ROM:075Fj
		ld	l, (ix+3Eh)
		ld	h, (ix+3Fh)

loc_76C:					    ; CODE XREF: ROM:078Aj
						    ; ROM:0793j
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ex	de, hl
		ld	a, 0F8h	; '¯'
		zand	b
		cp	80h ; 'Ä'
		jr	nz, loc_79F
		ld	a, b
		zadd	a, a
		zadd	a, 5Ch ; '\'
		ld	(loc_77F+1), a

loc_77F:					    ; DATA XREF: ROM:077Cw
		ld	hl, (off_15C)
		jp	(hl)
; ---------------------------------------------------------------------------

loc_783:					    ; DATA XREF: ROM:off_15Co
		ex	de, hl
		ld	(ix+39h), l
		ld	(ix+3Ah), h
		jr	loc_76C
; ---------------------------------------------------------------------------

loc_78C:					    ; DATA XREF: ROM:015Eo
		ex	de, hl
		ld	l, (ix+39h)
		ld	h, (ix+3Ah)
		jr	loc_76C
; ---------------------------------------------------------------------------

loc_795:					    ; DATA XREF: ROM:0160o
		ld	(ix+40h), c
		jr	loc_7B1
; ---------------------------------------------------------------------------

loc_79A:					    ; DATA XREF: ROM:0162o
		inc	(ix+38h)
		jr	loc_7B1
; ---------------------------------------------------------------------------

loc_79F:					    ; CODE XREF: ROM:0776j
		ld	l, (ix+2Ch)
		ld	h, (ix+2Dh)
		zadd	hl, bc
		ld	(ix+2Ch), l
		ld	(ix+2Dh), h
		ld	a, 1
		ld	(SavedNote), a

loc_7B1:					    ; CODE XREF: ROM:0798j
						    ; ROM:079Dj
		ld	(ix+3Eh), e
		ld	(ix+3Fh), d

loc_7B7:					    ; CODE XREF: ROM:0759j
						    ; ROM:0764j
		ld	a, (SavedNote)
		zor	a
		jr	z, loc_7D2
		ld	e, (ix+29h)
		ld	d, (ix+2Ah)
		zadd	hl, de
		ld	de, 7D2h
		push	de
		ld	a, (iy+0)
		zor	a
		jp	z, UpdateFrequency
		jp	j_u_PSGRoutine2_Safe
; ---------------------------------------------------------------------------

loc_7D2:					    ; CODE XREF: ROM:07BBj
		ld	a, (iy+0)
		zor	a
		jr	z, NoteLasts_PSG_or_FM
		bit	0, (ix+41h)
		jr	z, NoteLasts_PSG_or_FM
		dec	(ix+48h)
		jr	nz, NoteLasts_PSG_or_FM
		ld	e, (ix+46h)
		ld	d, (ix+47h)
		ld	a, (de)
		inc	de
		cp	0FFh
		jr	nz, loc_7F4
		inc	(ix+41h)
		jr	NoteLasts_PSG_or_FM
; ---------------------------------------------------------------------------

loc_7F4:					    ; CODE XREF: ROM:07EDj
		call	u_VolumeSub0F
		call	loc_FC7
		ld	a, (de)
		inc	de
		ld	(ix+48h), a
		ld	(ix+46h), e
		ld	(ix+47h), d

NoteLasts_PSG_or_FM:				    ; CODE XREF: ROM:06E0j
						    ; ROM:07D6j ...
		ld	a, (ix+0)
		cp	9
		call	z, SetYM_Port0
		xor	a			    ; a	= nop
		ld	(WriteYM_AutoPort_Safe), a
		ld	(WriteYM_Port0_Safe), a
		ld	(u_WritePSG_Safe), a
		ld	(u_WritePSG2_Safe), a
		ld	hl, BGM_CurrentChannel
		dec	(hl)			    ; do we have channels to process?
		jp	nz, UpdateBGM_ProcessChannel ; if yes, branch
		ld	a, (byte_104)
		xor	0FFh
		zand	60h
		cp	20h
		jp	z, UpdateBGM
		ret
; ---------------------------------------------------------------------------

LoadNote:					    ; DATA XREF: ROM:NoteCmdTableo
		ld	a, (ix+fm3_op)
		zor	a			    ; is FM3 is	special	mode?
		jr	z, PlayNote_Normal	    ; if not, branch
		cp	4			    ; have we done all 4 operators?
		jr	z, DoneFM3Ops		    ; if yes, branch
		ld	a, (de)			    ; load note
		inc	de
		zand	0Fh			    ; check it
		jr	z, NextFM3Op		    ; if note is 0, branch
		push	de
		zadd	a, a			    ; a	= Note*2
		inc	a			    ; a	= Note*2+1 (what for???)
		ld	b, 0
		ld	c, a
		ld	l, (ix+octave)
		ld	h, (ix+25h)		    ; hl = Octave offset
		zadd	hl, bc			    ; hl = Octave + Note
		ex	de, hl
		ld	a, (ix+fm3_op)
		zadd	a, a
		ld	b, 0
		ld	c, a
		ld	hl, YM_CH3FreqRegs-2	    ; load YM frequency	regs
		zadd	hl, bc
		ld	a, (de)
		ld	b, (hl)
		ld	c, a
		call	WriteYM_AutoPort_Safe	    ; set low byte
		inc	hl
		dec	de
		ld	a, (de)
		ld	b, (hl)
		ld	c, a
		call	WriteYM_AutoPort_Safe	    ; set high byte
		pop	de

NextFM3Op:					    ; CODE XREF: ROM:083Cj
		inc	(ix+fm3_op)		    ; do next operator
		jp	RunBGMTrack
; ---------------------------------------------------------------------------
YM_CH3FreqRegs:	db 0ADh,0A9h			    ; 0	; DATA XREF: ROM:0853t
		db 0AEh,0AAh			    ; 2
		db 0ACh,0A8h			    ; 4
; ---------------------------------------------------------------------------

DoneFM3Ops:					    ; CODE XREF: ROM:0836j
		ld	(ix+fm3_op), 1		    ; reset FM3	operator counter

PlayNote_Normal:				    ; CODE XREF: ROM:0832j
		ld	a, (ix+1)
		ld	(SavedNote), a
		ld	b, 28h			    ; YM key on/off register
		ld	c, (ix+note_off)
		bit	4, a
		call	z, WriteYM_Port0_Safe
		call	UpdateNote
		ld	a, b			    ; a	= Note
		zand	0Fh
		zor	a			    ; is note zero?
		jp	z, Track_NoteLasts	    ; if yes, branch
		call	CalcFrequency
		call	UpdateFrequency
		ld	a, (SavedNote)
		bit	4, a			    ; bit 4 is set to prevent note attack
		jp	nz, Track_NoteLasts
		ld	b, 28h
		ld	c, (ix+note_on)
		call	WriteYM_Port0_Safe
		call	sub_94E
		jp	Track_NoteLasts
; ---------------------------------------------------------------------------

LoadPSGNote:					    ; DATA XREF: ROM:0154o
		ld	a, (ix+1)
		ld	(SavedNote), a
		call	UpdateNote
		ld	a, b
		zand	0Fh
		zor	a
		jr	nz, loc_8C1
		call	sub_994
		jp	Track_NoteLasts
; ---------------------------------------------------------------------------

loc_8C1:					    ; CODE XREF: ROM:08B9j
		call	CalcFrequency
		call	j_u_PSGRoutine2_Safe
		ld	a, (SavedNote)
		bit	4, a
		jp	nz, Track_NoteLasts
		call	sub_94E
		ld	a, (ix+41h)
		zor	a
		jr	z, loc_8EF
		ld	l, (ix+42h)
		ld	h, (ix+43h)
		ld	(ix+46h), l
		ld	(ix+47h), h
		ld	(ix+41h), 1
		ld	(ix+48h), 1
		jp	Track_NoteLasts
; ---------------------------------------------------------------------------

loc_8EF:					    ; CODE XREF: ROM:08D6j
		ld	a, (ix+23h)
		call	u_FadeOutEffect
		call	loc_FC7
		jp	Track_NoteLasts
; ---------------------------------------------------------------------------

LoadPSGNoiseNote:				    ; DATA XREF: ROM:0156o
		call	UpdateNote
		ld	a, b
		zand	1Fh
		ld	(Struct_PSG4+24h), a
		jp	Track_NoteLasts

; =============== S U B	R O U T	I N E =======================================


UpdateNote:					    ; CODE XREF: ROM:0886p
						    ; ROM:08B2p ...
		ld	a, (de)			    ; load note
		inc	de
		ld	b, a
		ld	(ix+1),	a		    ; remember note
		ld	a, (ix+duration)
		bit	5, b			    ; if bit 5 is set, the duration follows the	note
		jr	z, @SkipDuration
		ld	a, (de)			    ; read duration
		inc	de

@SkipDuration:					    ; CODE XREF: UpdateNote+Bj
		ld	(ix+2),	a		    ; save note	duration
		ld	(ix+3),	e
		ld	(ix+4),	d		    ; save current position in track
		ret
; End of function UpdateNote


; =============== S U B	R O U T	I N E =======================================


CalcFrequency:					    ; CODE XREF: ROM:0890p
						    ; ROM:loc_8C1p
		ld	l, (ix+octave)
		ld	h, (ix+25h)		    ; load octave offset
		zadd	a, a
		ld	e, a
		ld	d, 0			    ; de = Note*2
		zadd	hl, de
		ld	e, (hl)
		inc	hl
		ld	d, (hl)			    ; de = Frequency
		ld	l, (ix+26h)
		ld	h, (ix+27h)
		zadd	hl, de			    ; add displacement to the frequency
		ld	(ix+29h), l
		ld	(ix+2Ah), h		    ; save calculated frequency
		ret
; End of function CalcFrequency


; =============== S U B	R O U T	I N E =======================================


UpdateFrequency:				    ; CODE XREF: ROM:07CCj
						    ; ROM:0893p
		ld	b, (iy+3)		    ; load YM frequency	regsiter: high byte
		ld	c, h
		call	WriteYM_AutoPort_Safe
		ld	a, 0FCh
		zadd	a, b
		ld	b, a			    ; load YM freqency register: low byte
		ld	c, l
		jp	WriteYM_AutoPort_Safe
; End of function UpdateFrequency

j_u_PSGRoutine2_Safe:
;	db	00, 00, 00 ; #################
		jp	u_WritePSG2_Safe

; =============== S U B	R O U T	I N E =======================================


sub_94E:					    ; CODE XREF: ROM:08A6p
						    ; ROM:08CFp
		ld	a, (ix+38h)
		zor	a
		jr	z, loc_96A
		ld	(ix+38h), 1
		ld	l, (ix+3Bh)
		ld	h, (ix+3Ch)
		ld	(ix+3Eh), l
		ld	(ix+3Fh), h
		ld	a, (ix+3Dh)
		ld	(ix+40h), a

loc_96A:					    ; CODE XREF: sub_94E+4j
		ld	a, (ix+2Eh)
		zor	a
		jr	z, loc_98B
		ld	(ix+33h), a
		ld	l, (ix+2Fh)
		ld	h, (ix+30h)
		ld	(ix+34h), l
		ld	(ix+35h), h
		ld	a, (ix+31h)
		ld	(ix+36h), a
		ld	a, (ix+32h)
		ld	(ix+37h), a

loc_98B:					    ; CODE XREF: sub_94E+20j
		ld	(ix+2Ch), 0
		ld	(ix+2Dh), 0
		ret
; End of function sub_94E


; =============== S U B	R O U T	I N E =======================================


sub_994:					    ; CODE XREF: ROM:loc_701p
						    ; ROM:08BBp
		ld	a, (ix+41h)
		zor	a
		jr	nz, loc_99D
		jp	loc_FC7
; ---------------------------------------------------------------------------

loc_99D:					    ; CODE XREF: sub_994+4j
		cp	3
		ret	nc
		ld	(ix+41h), 3
		ld	(ix+48h), 1
		ld	l, (ix+44h)
		ld	h, (ix+45h)
		ld	(ix+46h), l
		ld	(ix+47h), h
		ret
; End of function sub_994


; =============== S U B	R O U T	I N E =======================================


LoadChannel:					    ; CODE XREF: u_FadeOutBGMLoop:loc_5DCp
						    ; ROM:0643p ...
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl			    ; de = (hl)+
		push	de			    ; ix = de
		pop	ix
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl			    ; de = (hl)+
		push	de			    ; iy = de
		pop	iy
		ret
; End of function LoadChannel


; =============== S U B	R O U T	I N E =======================================

; hl = Pointer

GetVoicePointer:				    ; CODE XREF: ROM:0A07p
						    ; ROM:loc_A9Bp ...
		zadd	a, 0Ch
; End of function GetVoicePointer


; =============== S U B	R O U T	I N E =======================================

; hl = Pointer

GetBGMPointer:					    ; CODE XREF: InitBGMPlayback+14p
		zadd	a, a			    ; a	= n*2
		inc	a			    ; a	= n*2 +	1
		ld	b, 0
		ld	c, a
		ld	hl, (BGMOffset)
		zadd	hl, bc
		ld	c, (hl)			    ; bc = (hl)
		inc	hl
		ld	b, (hl)
		ld	hl, (BGMOffset)
		zadd	hl, bc			    ; hl = BGM offset +	bc
		ret
; End of function GetBGMPointer


; =============== S U B	R O U T	I N E =======================================


u_VolumeSub0F:					    ; CODE XREF: ROM:loc_7F4p
		zadd	a, (ix+volume)
		zsub	0Fh
		jr	c, ZeroVolume

u_FadeOutEffect:				    ; CODE XREF: ROM:08F2p
						    ; ROM:0A4Cp
		ld	hl, u_FadeOutCnt
		zsub	(hl)
		ret	nc

ZeroVolume:					    ; CODE XREF: u_VolumeSub0F+5j
		xor	a			    ; set volume to zero (total	silence)
		ret
; End of function u_VolumeSub0F

; ---------------------------------------------------------------------------

Flag01_LoadFMVoice:				    ; DATA XREF: ROM:FlagsTableo
		ld	b, (iy+7)		    ; load YM register 80h+ (Release Rate)
		ld	c, 0Fh			    ; set instant Release Rate (RR)
		call	WriteYM_AutoPort_Safe	    ; do operator 1
		ld	a, 4
		zadd	a, b
		ld	b, a
		call	WriteYM_AutoPort_Safe	    ; do operator 2
		ld	a, 4
		zadd	a, b
		ld	b, a
		call	WriteYM_AutoPort_Safe	    ; do operator 3
		ld	a, 4
		zadd	a, b
		ld	b, a
		call	WriteYM_AutoPort_Safe	    ; do operator 4
		ld	a, (de)			    ; load instrument number
		inc	de
		ld	(ix+41h), a		    ; set it as	current	instrument
		call	GetVoicePointer		    ; hl = Pointer
		ld	a, (iy+4)		    ; load YM register 30h+

@SendVoiceLoop:					    ; CODE XREF: ROM:0A18j
		ld	b, a
		ld	c, (hl)
		inc	hl
		call	WriteYM_AutoPort_Safe
		ld	a, 4
		zadd	a, b
		cp	8Fh			    ; have we filled all the registers?
		jr	c, @SendVoiceLoop	    ; if not, repeat
		ld	a, (hl)			    ; load algorithm
		ld	c, a
		ld	b, (iy+5)		    ; load YM algorithm	register
		zand	7			    ; mask algorithm from feedback
		ld	(ix+42h), a		    ; save algorithm
		call	WriteYM_AutoPort_Safe
		ld	bc, -11h
		zadd	hl, bc
		ld	(ix+43h), l
		ld	(ix+44h), h		    ; save pointer to operator 4 TL
		ld	c, (ix+23h)
		jp	UpdateVolume
; ---------------------------------------------------------------------------

Flag03_SetVolume:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de

SetVolume:					    ; CODE XREF: ROM:0A83j
						    ; ROM:0A89j ...
		ld	(ix+volume), a		    ; save volume

SetVolume2:					    ; CODE XREF: ROM:06A6p
		ld	c, a
		ld	a, (iy+0)		    ; load channel type
		zadd	a, a
		zadd	a, 64h
		ld	(loc_A46+1), a

loc_A46:					    ; DATA XREF: ROM:0A43w
		ld	hl, (VolCmdTable)
		jp	(hl)
; ---------------------------------------------------------------------------

UpdateVolume:					    ; CODE XREF: u_FadeOutBGMLoop:loc_5F8p
						    ; ROM:0A34j
						    ; DATA XREF: ...
		push	de
		ld	a, c
		call	u_FadeOutEffect
		ld	b, 0
		ld	c, a
		ld	hl, VolumeTable
		zadd	hl, bc
		ex	de, hl
		ld	a, (ix+algorithm)	    ; load algorithm
		zadd	a, 6Eh
		ld	(loc_A5F+1), a

loc_A5F:					    ; DATA XREF: ROM:0A5Cw
		ld	a, (TLTransferCnt)	    ; set TL transfer count based on the algorithm
		ld	b, a
		ld	c, (iy+6)		    ; load YM Release Rate register (will be decreased to TL registers)
		ld	l, (ix+43h)
		ld	h, (ix+44h)		    ; hl = Operartor 4 TL for the current voice

@SendTLLoop:					    ; CODE XREF: ROM:0A7Aj
		ld	a, -4
		zadd	a, c
		ld	c, a			    ; c	= YM register for the current operator's TL
		push	bc
		ld	b, c
		ld	a, (de)			    ; load volume attenuation
		zadd	a, (hl)			    ; add operator's TL to it
		ld	c, a
		call	WriteYM_AutoPort_Safe
		dec	hl			    ; previous operator	TL
		pop	bc
		djnz	@SendTLLoop
		pop	de
		ret
; ---------------------------------------------------------------------------

locret_A7E:					    ; DATA XREF: ROM:0166o
						    ; ROM:0168o
		ret
; ---------------------------------------------------------------------------

Flag04_VolumeUp:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (ix+volume)
		inc	a
		jr	SetVolume
; ---------------------------------------------------------------------------

Flag05_VolumeDown:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (ix+volume)
		dec	a
		jr	SetVolume
; ---------------------------------------------------------------------------

Flag06_AlterVolume:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		zadd	a, (ix+volume)
		jr	SetVolume
; ---------------------------------------------------------------------------

Flag02_LoadPSGVoice:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)			    ; read voice number
		inc	de
		zor	a
		jr	nz, loc_A9B		    ; if voice isn't zero, branch
		ld	(ix+41h), a
		ret
; ---------------------------------------------------------------------------

loc_A9B:					    ; CODE XREF: ROM:0A95j
		call	GetVoicePointer		    ; hl = Pointer
		ld	(ix+42h), l
		ld	(ix+43h), h
		ld	a, (de)
		inc	de
		call	GetVoicePointer		    ; hl = Pointer
		ld	(ix+44h), l
		ld	(ix+45h), h
		ld	(ix+41h), 4
		xor	a
		jp	loc_FC7
; ---------------------------------------------------------------------------

Flag07_SetOctave:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		dec	a
		ld	b, a			    ; b	= x
		zadd	a, b			    ; a	= 2x
		zadd	a, b			    ; a	= 3x
		zadd	a, a			    ; a	= 6x
		zadd	a, a			    ; a	= 12x
		zadd	a, a			    ; a	= 24x
		ld	b, 0
		ld	c, a			    ; bc = 24x
		ld	l, (iy+1)
		ld	h, (iy+2)
		zadd	hl, bc
		ld	(ix+24h), l
		ld	(ix+25h), h
		ret
; ---------------------------------------------------------------------------

Flag08_NextOctave:				    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+24h)
		ld	h, (ix+25h)
		ld	bc, 18h
		zadd	hl, bc
		ld	(ix+24h), l
		ld	(ix+25h), h
		ret
; ---------------------------------------------------------------------------

Flag09_PrevOctave:				    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+24h)
		ld	h, (ix+25h)
		ld	bc, 0FFE8h
		zadd	hl, bc
		ld	(ix+24h), l
		ld	(ix+25h), h
		ret
; ---------------------------------------------------------------------------

Flag0A_AlterOctave:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	b, a			    ; b	= x
		zadd	a, b			    ; a	= 2x
		zadd	a, b			    ; a	= 3x
		zadd	a, a			    ; a	= 6x
		zadd	a, a			    ; a	= 12x
		zadd	a, a			    ; a	= 24x
		ld	c, a			    ; c	= 24x
		rla
		ld	a, 0
		sbc	a, a
		ld	b, a			    ; b	= 0FFh or 00h
		ld	l, (ix+24h)
		ld	h, (ix+25h)
		zadd	hl, bc
		ld	(ix+24h), l
		ld	(ix+25h), h
		ret
; ---------------------------------------------------------------------------

Flag0B_u_Set22h:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	(ix+22h), a
		ret
; ---------------------------------------------------------------------------

Flag0C_u_Set28h:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	(ix+28h), a
		ret
; ---------------------------------------------------------------------------

Flag0D_SendYMCommand:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	b, a
		ld	a, (de)
		inc	de
		ld	c, a
		jp	WriteYM_AutoPort_Safe
; ---------------------------------------------------------------------------

Flag0E_SetRepeat:				    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+5)
		ld	h, (ix+6)		    ; load stack pointer
		inc	hl			    ; allocate 3 bytes in stack
		inc	hl
		inc	hl
		ld	(ix+5),	l
		ld	(ix+6),	h		    ; save new stack pointer
		ld	a, (de)			    ; read repeat count
		inc	de
		ld	(hl), a			    ; store repeat count
		inc	hl
		ld	(hl), e			    ; store track position to repeat from
		inc	hl
		ld	(hl), d
		ret
; ---------------------------------------------------------------------------

Flag0F_Repeat:					    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+5)
		ld	h, (ix+6)		    ; load stack pointer
		dec	(hl)			    ; decrease repeat count
		jr	z, FreeStack		    ; if it's zero, branch
		inc	hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)			    ; otherwise, set track position to repeat position
		ret
; ---------------------------------------------------------------------------

FreeStack:					    ; CODE XREF: ROM:0B42j
						    ; ROM:0B59j
		dec	hl
		dec	hl
		dec	hl			    ; free 3 bytes from	stack
		ld	(ix+5),	l
		ld	(ix+6),	h		    ; save new stack pointer
		ret
; ---------------------------------------------------------------------------

Flag10_StopRepeat:				    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+5)
		ld	h, (ix+6)
		jr	FreeStack
; ---------------------------------------------------------------------------

Flag11:						    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	b, a
		ld	a, (de)
		inc	a
		cp	b
		jr	nz, loc_B70
		xor	a
		ld	(de), a
		inc	de
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		ld	hl, (BGMOffset)
		zadd	hl, de
		ex	de, hl
		ret
; ---------------------------------------------------------------------------

loc_B70:					    ; CODE XREF: ROM:0B61j
		ld	(de), a
		inc	de
		inc	de
		inc	de
		ret
; ---------------------------------------------------------------------------

Flag12_JumpTo:					    ; CODE XREF: ROM:0B94j
						    ; DATA XREF: ROM:FlagsTableo
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)			    ; load jump	offset
		ld	hl, (BGMOffset)
		zadd	hl, de
		ex	de, hl
		ret
; ---------------------------------------------------------------------------

Flag13_Call:					    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+16h)
		ld	h, (ix+17h)		    ; load current position in call stack
		inc	hl
		inc	hl			    ; allocate 2 bytes in the stack
		ld	(ix+16h), l
		ld	(ix+17h), h		    ; save new position	in stack
		inc	de
		inc	de
		ld	(hl), e
		inc	hl
		ld	(hl), d			    ; store return position
		dec	de
		dec	de
		jr	Flag12_JumpTo
; ---------------------------------------------------------------------------

Flag14_Return:					    ; DATA XREF: ROM:FlagsTableo
		ld	l, (ix+16h)
		ld	h, (ix+17h)		    ; load current position in call stack
		ld	e, (hl)
		inc	hl
		ld	d, (hl)			    ; load return position
		dec	hl
		dec	hl
		dec	hl
		ld	(ix+16h), l
		ld	(ix+17h), h
		ret
; ---------------------------------------------------------------------------

Flag15:						    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	(ix+2Eh), a
		zor	a
		ret	z
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ex	de, hl
		ld	(ix+2Fh), l
		ld	(ix+30h), h
		ld	(ix+34h), 0
		ld	(ix+35h), 0
		ld	a, (de)
		inc	de
		ld	(ix+31h), a
		ld	a, (de)
		inc	de
		ld	(ix+32h), a
		ret
; ---------------------------------------------------------------------------

Flag16_AlterFrequency:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	(ix+26h), a
		rla
		ld	a, 0
		sbc	a, a
		ld	(ix+27h), a
		ret
; ---------------------------------------------------------------------------

Flag17:						    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	(ix+38h), a
		zor	a
		ret	z
		ld	(ix+38h), 2
		call	GetVoicePointer		    ; hl = Pointer
		ld	(ix+3Bh), l
		ld	(ix+3Ch), h
		ld	a, (de)
		inc	de
		ld	(ix+3Dh), a
		ret
; ---------------------------------------------------------------------------

Flag18_SetSpecFM3:				    ; DATA XREF: ROM:FlagsTableo
		ld	(ix+45h), 1
		ret
; ---------------------------------------------------------------------------

Flag19_ResetSpecFM3:				    ; DATA XREF: ROM:FlagsTableo
		ld	(ix+45h), 0
		ret
; ---------------------------------------------------------------------------

Flag00_AlterTempo:				    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de

; =============== S U B	R O U T	I N E =======================================


SetBGMTempo:					    ; CODE XREF: InitBGMPlayback+49p
		ld	b, 26h
		ld	c, a
		inc	c
		jp	WriteYM_Port0
; End of function SetBGMTempo

; ---------------------------------------------------------------------------

Flag1A_PanLR:					    ; DATA XREF: ROM:FlagsTableo
		ld	c, 0C0h
		ld	b, (iy+8)
		jp	WriteYM_AutoPort_Safe
; ---------------------------------------------------------------------------

Flag1B_PanLeft:					    ; DATA XREF: ROM:FlagsTableo
		ld	c, 80h
		ld	b, (iy+8)
		jp	WriteYM_AutoPort_Safe
; ---------------------------------------------------------------------------

Flag1C_PanRight:				    ; DATA XREF: ROM:FlagsTableo
		ld	c, 40h
		ld	b, (iy+8)
		jp	WriteYM_AutoPort_Safe
; ---------------------------------------------------------------------------

Flag1D:						    ; DATA XREF: ROM:FlagsTableo
		ld	a, (de)
		inc	de
		ld	(u_68kTrueStory), a
		ret
; ---------------------------------------------------------------------------

LoadBGMFromROM:					    ; CODE XREF: UpdateSounds+2Ap
		ld	a, (ROMBank+1)
		rlca
		ld	(6000h), a
		ld	a, (ROMBank)
		ld	b, 8

@SetROMBank:					    ; CODE XREF: ROM:0C37j
		ld	(6000h), a
		rrca
		djnz	@SetROMBank
		ld	a, (BGMNum)
		zadd	a, a
		zadd	a, 1
		ld	(loc_C42+1), a

loc_C42:					    ; DATA XREF: ROM:0C3Fw
		ld	hl, (8001h)
		ld	(BGMOffset), hl

; =============== S U B	R O U T	I N E =======================================


InitBGMPlayback:				    ; CODE XREF: StopBGM+16p
		ld	a, 1
		ld	(BGMPlaying), a		    ; set BGM as playing
		ld	a, 0Ah
		ld	(BGM_CurrentChannel), a
		ld	hl, ChannelPointers

@BGMLoadChanLoop:				    ; CODE XREF: InitBGMPlayback+44j
		call	LoadChannel
		ex	de, hl			    ; remember hl to de
		ld	a, (ix+0)
		call	GetBGMPointer		    ; hl = Pointer
		ld	(ix+3),	l
		ld	(ix+4),	h		    ; save current position in track
		ld	(ix+1),	0
		ld	(ix+2),	1		    ; set note duration
		push	ix
		pop	hl			    ; hl = ix
		ld	bc, 4
		zadd	hl, bc			    ; hl = ix+4
		ld	(ix+5),	l
		ld	(ix+6),	h
		push	ix
		pop	hl			    ; hl = ix
		ld	bc, 16h
		zadd	hl, bc			    ; hl = ix +	16h
		ld	(ix+16h), l
		ld	(ix+17h), h
		ld	hl, BGM_CurrentChannel
		dec	(hl)			    ; do we have channels left?
		ex	de, hl			    ; restore hl from de
		jp	nz, @BGMLoadChanLoop	    ; if yes, branch
		ld	a, 0E9h
		call	SetBGMTempo
		ret
; End of function InitBGMPlayback


; =============== S U B	R O U T	I N E =======================================


StopBGM:					    ; CODE XREF: UpdateSounds+27p
						    ; UpdateSounds:StopBGM2p ...
		xor	a
		ld	(u_WritePSG_Safe), a
		ld	(u_WritePSG2_Safe), a
		ld	(WriteYM_AutoPort_Safe), a
		ld	(WriteYM_Port0_Safe), a
		call	SetYM_Port0
		ld	hl, IdleBGM
		ld	(BGMOffset), hl
		call	InitBGMPlayback
		call	UpdateBGM
		xor	a
		ld	(BGMPlaying), a		    ; set BGM as not playing
		ld	(u_68kTrueStory), a
		ld	(u_FadeOutCnt),	a
		ret
; End of function StopBGM

; ---------------------------------------------------------------------------
BGMOffset:	dw 0				    ; DATA XREF: GetBGMPointer+5r
						    ; GetBGMPointer+Cr	...
ChannelOffset:	dw 0				    ; DATA XREF: ROM:0626w
						    ; ROM:UpdateBGM_ProcessChannelr ...
BGM_CurrentChannel: db 0				    ; DATA XREF: u_FadeOutBGMLoop+2w
						    ; u_FadeOutBGMLoop+41o ...
u_FadeOutCnt:	db 0				    ; DATA XREF: UpdateSounds:FadeOutBGMr
						    ; UpdateSounds+19w	...
u_BGMUpdCounter: db 0				    ; DATA XREF: UpdateSounds+1Ew
						    ; ROM:062Fo ...
SavedNote:	db 0				    ; DATA XREF: ROM:0705w
						    ; ROM:0724w ...
ChannelPointers: dw Struct_FM1,Data_FM1_FM4	    ; 0	; DATA XREF: u_FadeOutBGMLoop+5o
						    ; ROM:0623o ...
		dw Struct_FM2,Data_FM2_FM5	    ; 2
		dw Struct_FM3,Data_FM3_FM6	    ; 4
		dw Struct_PSG1,Data_PSG1	    ; 6
		dw Struct_PSG2,Data_PSG2	    ; 8
		dw Struct_PSG3,Data_PSG3	    ; 10
		dw Struct_PSG4,Data_PSG4	    ; 12
		dw Struct_FM4,Data_FM1_FM4	    ; 14
		dw Struct_FM5,Data_FM2_FM5	    ; 16
		dw Struct_FM6,Data_FM3_FM6	    ; 18
Data_FM1_FM4:	db 0				    ; DATA XREF: ROM:ChannelPointerso
		dw FMFrequencies-2
		db 0A4h, 30h,0B0h, 50h,	80h,0B4h
Data_FM2_FM5:	db 0				    ; DATA XREF: ROM:ChannelPointerso
		dw FMFrequencies-2
		db 0A5h, 31h,0B1h, 51h,	81h,0B5h
Data_FM3_FM6:	db 0				    ; DATA XREF: ROM:ChannelPointerso
		dw FMFrequencies-2
		db 0A6h, 32h,0B2h, 52h,	82h,0B6h
Data_PSG1:	db 1				    ; DATA XREF: ROM:ChannelPointerso
		dw FMFrequencies+0A6h
		db  80h, 90h
Data_PSG2:	db    1				    ; 0	; DATA XREF: ROM:ChannelPointerso
		dw FMFrequencies+0A6h
		db 0A0h,0B0h
Data_PSG3:	db    1				    ; 0	; DATA XREF: ROM:ChannelPointerso
		dw FMFrequencies+0A6h
		db 0C0h,0D0h
Data_PSG4:	db    2				    ; 0	; DATA XREF: ROM:ChannelPointerso
Struct_FM1:	db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,0F0h,	 0; 40h
Struct_FM2:	db    1,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,0F1h,	 1; 40h
Struct_FM3:	db    2,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,0F2h,	 2; 40h
Struct_FM4:	db    7,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,0F4h,	 4; 40h
Struct_FM5:	db    8,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,0F5h,	 5; 40h
Struct_FM6:	db    9,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,0F6h,	 6; 40h
Struct_PSG1:	db    3,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0; 40h
Struct_PSG2:	db    4,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0; 40h
Struct_PSG3:	db    5,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 20h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 30h
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0; 40h
Struct_PSG4:	db    6,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 0
						    ; DATA XREF: ROM:ChannelPointerso
		db    0,   0,	0,   0,	  0,   0,   0,	 0,   0,   0,	0,   0,	  0,   0,   0,	 0; 10h
		db    0,   0,	0,   0,	  0	    ; 20h
; ---------------------------------------------------------------------------

loc_FC7:					    ; CODE XREF: ROM:07F7p
						    ; ROM:08F5p ...
		ld	(ix+2Bh), a

u_WritePSG_Safe:				    ; DATA XREF: ROM:066Aw
						    ; ROM:0814w ...
		znop

; =============== S U B	R O U T	I N E =======================================


u_WritePSG:					    ; CODE XREF: u_FadeOutBGMLoop:loc_60Ap
						    ; ROM:068Dp
		zand	0Fh
		zor	(iy+4)

loc_FD0:					    ; CODE XREF: ROM:1754p
		xor	0Fh
		ld	(7F11h), a
		ret
; End of function u_WritePSG

; ---------------------------------------------------------------------------

u_WritePSG2_Safe:				    ; CODE XREF: j_u_PSGRoutine2_Safej
						    ; DATA XREF: ROM:066Dw ...
		znop

; =============== S U B	R O U T	I N E =======================================


u_WritePSG2:					    ; CODE XREF: ROM:0687p
		ld	a, 0Fh
		zand	l
		zor	(iy+3)

loc_FDD:					    ; CODE XREF: ROM:1702p
		ld	(7F11h), a
		ld	a, 0F0h	; ''
		zand	l
		ld	l, a
		ld	a, 0Fh
		zand	h
		zor	l
		rrca
		rrca
		rrca
		rrca
		zand	3Fh ; '?'
		ld	(7F11h), a
		ret
; End of function u_WritePSG2


; =============== S U B	R O U T	I N E =======================================


WriteYM_AutoPort_Safe:				    ; CODE XREF: ROM:085Ap
						    ; ROM:0862p ...
		znop

WriteYM_AutoPort:				    ; CODE XREF: WriteYM_AutoPort_Safe+5j
		ld	a, (4000h)
		rla
		jr	c, WriteYM_AutoPort
		ld	a, b

YM_PortReg_Dyn:					    ; DATA XREF: SetYM_Port0+3w
						    ; SetYM_Port1+3w
		ld	(4000h), a
		znop
		znop
		znop
		ld	a, c

YM_PortVal_Dyn:					    ; DATA XREF: SetYM_Port0+7w
						    ; SetYM_Port1+7w
		ld	(4001h), a
		ret
; End of function WriteYM_AutoPort_Safe

; ---------------------------------------------------------------------------

WriteYM_Port0_Safe:				    ; CODE XREF: ROM:06FCp
						    ; ROM:0883p ...
		znop				    ; sound driver changes this	to 'ret' under certain conditions

; =============== S U B	R O U T	I N E =======================================


WriteYM_Port0:					    ; CODE XREF: UpdateSounds+7Ap
						    ; UpdateSounds+99p	...
		ld	a, (4000h)
		rla
		jr	c, WriteYM_Port0
		ld	a, b
		ld	(4000h), a
		znop
		znop
		znop
		ld	a, c
		ld	(4001h), a
		ret
; End of function WriteYM_Port0


; =============== S U B	R O U T	I N E =======================================


SetYM_Port0:					    ; CODE XREF: u_FadeOutBGMLoop+3Ep
						    ; ROM:080Ap ...
		ld	hl, 4000h
		ld	(YM_PortReg_Dyn+1), hl
		inc	hl
		ld	(YM_PortVal_Dyn+1), hl
		ret
; End of function SetYM_Port0


; =============== S U B	R O U T	I N E =======================================


SetYM_Port1:					    ; CODE XREF: u_FadeOutBGMLoop+11p
						    ; ROM:064Ep
		ld	hl, 4002h
		ld	(YM_PortReg_Dyn+1), hl
		inc	hl
		ld	(YM_PortVal_Dyn+1), hl
		ret
; End of function SetYM_Port1


; =============== S U B	R O U T	I N E =======================================


GetYMState:					    ; CODE XREF: ROM:loc_4A4p
						    ; UpdateSounds:loc_556p ...
		ld	a, (4000h)
		ret
; End of function GetYMState

; ---------------------------------------------------------------------------
		db    0
off_1033:	dw loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0 ; DATA XREF:	ROM:163Do
		dw loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0
		dw loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0
		dw loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0,loc_0
		dw byte_10B1,byte_10CF,byte_1110,byte_15F1,byte_1142,byte_1177,byte_11AC,byte_1215
		dw byte_1288,byte_1253,byte_12C5,byte_12ED,byte_1352,byte_139E,byte_13CA,byte_140C
		dw byte_1443,byte_149A,byte_1512,byte_1567,byte_159D,byte_15F1,byte_15F1,byte_15F1
		dw byte_15F1,byte_15F1,byte_15F1,byte_15F1,byte_15F1,byte_15F1,byte_15F1
byte_10B1:	db  0Ah,   3, 50h, 0Ch,	30h, 0Ch, 14h,	 4, 4Eh, 96h,	0, 2Eh,0C8h,   0, 14h,	 6
						    ; DATA XREF: ROM:off_1033o
		db  4Fh, 6Ah,0FFh, 2Fh,	1Eh,   0, 82h, 15h, 51h,0FEh, 31h,0FEh,	15h,0FFh
byte_10CF:	db  0Ah,   3, 50h, 0Bh,	30h, 0Bh, 4Eh, 32h,   0, 2Eh, 3Ch,   0,	14h,   4, 4Fh,0FBh
						    ; DATA XREF: ROM:off_1033o
		db 0FFh, 2Fh,0FBh,0FFh,	82h, 15h, 14h,	 5, 14h,   3, 4Fh,   3,	  0, 2Fh,   4,	 0
		db  81h, 15h, 4Fh,0F7h,0FFh, 2Fh,0F4h,0FFh, 15h, 14h,	3, 14h,	  5, 4Fh, 0Ah,	 0
		db  2Fh, 0Fh,	0, 82h,	15h, 4Fh,0CEh,0FFh, 2Fh,0B5h,0FFh, 51h,0FEh, 31h,0FEh, 15h
		db 0FFh
byte_1110:	db  0Ah,   3, 50h, 0Ch,	30h, 0Ch, 70h, 0Ch, 12h,   4, 14h,   3,	4Eh, 64h,   0, 2Eh
						    ; DATA XREF: ROM:off_1033o
		db  64h,   1, 12h,   4,	14h,   3, 14h,	 4, 4Fh,0C4h,0FFh, 2Fh,	64h,   0, 81h, 4Fh
		db  6Eh,   0, 2Fh, 88h,0FFh, 81h, 15h, 13h,   1, 15h, 51h,0FEh,	31h,0FEh, 71h,0FEh
		db  15h,0FFh
byte_1142:	db  14h,   7, 10h, 0Dh,	30h, 0Dh, 50h, 0Dh, 0Eh,0FAh,	0, 2Eh,0DCh,   0, 14h,	 8
						    ; DATA XREF: ROM:off_1033o
		db  4Eh, 50h,	0, 14h,	14h, 0Fh,0C8h,	 0, 2Fh,0BEh,	0, 4Fh,	46h,   0, 81h, 0Fh
		db  33h,0FFh, 2Fh, 3Dh,0FFh, 81h, 15h, 0Fh, 5Ah,   0, 2Fh, 5Ah,	  0, 11h,0FFh, 31h
		db 0FFh, 51h,0FFh, 15h,0FFh
byte_1177:	db  14h,   7, 10h, 0Dh,	30h, 0Dh, 50h, 0Bh, 4Eh,0FAh,	0, 14h,	  8, 0Eh, 50h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  2Eh, 7Dh,	0, 14h,	  5, 0Fh, 3Ch,	 0, 2Fh, 14h,	0, 4Fh,0B0h,0FFh, 82h, 15h
		db  14h,   5, 0Fh, 3Ch,	  0, 2Fh, 14h,	 0, 4Fh, 50h,	0, 82h,	15h, 11h,0FFh, 31h
		db 0FFh, 51h,0FFh, 15h,0FFh
byte_11AC:	db  14h,   7, 10h, 0Dh,	30h, 0Dh, 50h, 0Bh, 0Eh, 64h,	0, 2Eh,	78h,   0, 4Eh, 8Ch
						    ; DATA XREF: ROM:off_1033o
		db    0, 14h,	9, 0Fh,	64h,   0, 2Fh, 5Ah,   0, 4Fh,0B4h,   0,	82h, 0Fh, 97h,0FFh
		db  2Fh,0A1h,0FFh, 4Fh,	47h,0FFh, 82h, 15h, 14h, 0Ch, 0Fh, 64h,	  0, 2Fh, 5Ah,	 0
		db  4Fh,0B4h,	0, 82h,	0Fh, 9Ch,0FFh, 2Fh,0A6h,0FFh, 4Fh, 4Ch,0FFh, 82h, 15h, 14h
		db    4, 14h,	9, 0Fh,	7Dh,   0, 2Fh, 73h,   0, 4Fh, 69h,   0,	82h, 0Fh, 97h,0FFh
		db  2Fh,0A1h,0FFh, 4Fh,0ABh,0FFh, 82h, 15h, 0Fh, 4Ch,0FFh, 2Fh,	4Ch,0FFh, 4Fh, 4Ch
		db 0FFh, 11h,0FEh, 31h,0FEh, 51h,0FEh, 15h,0FFh
byte_1215:	db  32h,   7, 10h, 0Dh,	30h, 0Dh, 50h, 0Dh, 14h,   3, 0Eh, 32h,	  0, 2Eh, 14h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  4Eh, 23h,	0, 14h,	  5, 0Fh, 14h,	 0, 2Fh,0FEh,0FFh, 4Fh,	32h,   0, 82h, 15h
		db  0Eh, 1Eh,	0, 2Eh,	0Ah,   0, 4Eh, 14h,   0, 14h,	5, 0Fh,	0Ah,   0, 2Fh,0FFh
		db 0FFh, 4Fh, 14h,   0,	82h, 15h, 11h,0FEh, 31h,0FEh, 51h,0FEh,	15h,0FFh
byte_1253:	db  28h,   7, 50h, 0Eh,	30h, 0Eh, 10h, 0Eh, 4Eh,0C8h,	0, 2Eh,	96h,   0, 0Eh, 78h
						    ; DATA XREF: ROM:off_1033o
		db    0, 14h,	8, 14h,	  4, 4Fh,0ECh,0FFh, 2Fh, 0Fh,	0, 0Fh,0ECh,0FFh, 83h, 15h
		db  14h,   4, 4Fh, 12h,	  0, 2Fh,0EFh,0FFh, 0Fh, 13h,	0, 83h,	15h, 51h,0FFh, 31h
		db 0FFh, 11h,0FFh, 15h,0FFh
byte_1288:	db  32h,   7, 10h, 0Fh,	30h, 0Fh, 50h, 0Fh, 70h, 0Eh, 2Eh, 64h,	  0, 4Eh, 96h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  14h,   4, 12h,   4,	0Eh, 32h,   0, 14h,   3, 14h, 0Ah, 0Fh,	64h,   0, 2Fh, 32h
		db    0, 4Fh, 3Ch,   0,	81h, 0Fh,0B0h,0FFh, 81h, 15h, 2Fh,0DDh,0FCh, 4Fh,0CEh,0FCh
		db  13h,   1, 15h, 11h,0FFh, 31h,0FFh, 51h,0FFh, 71h,0FFh, 15h,0FFh
byte_12C5:	db  2Dh,   7, 10h, 0Eh,	30h, 0Eh, 50h, 0Eh, 14h,   4, 0Eh, 96h,	  0, 2Eh,0C8h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  4Eh, 32h,	0, 14h,	14h, 0Fh,0FBh,0FFh, 2Fh,0FBh,0FFh, 4Fh,	0Ah,   0, 83h, 15h
		db  11h,0FEh, 31h,0FEh,	51h,0FEh, 15h,0FFh
byte_12ED:	db  32h,   7, 10h, 0Fh,	30h, 0Fh, 50h, 0Fh, 14h,   2, 0Eh, 50h,	  0, 2Eh, 78h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  4Eh, 14h,	0, 14h,	0Dh, 0Fh, 32h,	 0, 2Fh, 46h,	0, 4Fh,0C8h,   0, 82h, 15h
		db  15h, 14h,	3, 0Eh,	  0,   0, 2Eh, 1Eh,   0, 4Eh, 14h,   0,	14h, 0Eh, 0Fh, 32h
		db    0, 2Fh, 46h,   0,	4Fh, 64h,   0, 82h, 15h, 15h, 70h, 0Fh,	14h,   5, 12h,	 4
		db  14h,   3, 0Eh,   0,	  1, 2Eh,0E6h,	 1, 4Eh, 3Ch,	0, 14h,	0Eh, 0Fh, 28h,	 0
		db  2Fh, 82h,	0, 4Fh,	28h,   0, 82h, 15h, 13h,   1, 15h, 11h,0FFh, 31h,0FFh, 51h
		db 0FFh, 71h,0FFh, 15h,0FFh
byte_1352:	db  28h,   7, 10h, 0Eh,	30h, 0Eh, 50h, 0Eh, 14h,   3, 0Eh, 50h,	  0, 2Eh, 78h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  4Eh, 14h,	0, 14h,	0Dh, 0Fh, 32h,	 0, 2Fh, 46h,	0, 4Fh,0C8h,   0, 82h, 15h
		db  15h, 70h, 0Fh, 14h,	  4, 12h,   4, 14h,   3, 0Eh,	0,   1,	2Eh,0E6h,   1, 4Eh
		db  3Ch,   0, 14h,   9,	0Fh, 28h,   0, 2Fh, 96h,   0, 4Fh, 28h,	  0, 82h, 15h, 13h
		db    1, 15h, 11h,0FFh,	31h,0FFh, 51h,0FFh, 71h,0FFh, 15h,0FFh
byte_139E:	db  12h,   3, 50h, 0Ch,	30h, 0Ch, 70h, 0Eh, 12h,   7, 14h,   2,	4Eh, 14h,   0, 2Eh
						    ; DATA XREF: ROM:off_1033o
		db  28h,   0, 81h, 14h,	0Fh, 4Fh,0DCh,	 0, 2Fh,0DCh,	0, 81h,	4Fh, 4Ch,0FFh, 2Fh
		db  4Ch,0FFh, 81h, 15h,	51h,0FEh, 31h,0FEh, 71h,0FEh, 15h,0FFh
byte_13CA:	db  14h,   3, 30h, 0Dh,	50h, 0Dh, 2Eh, 96h,   0, 4Eh, 78h,   0,	82h, 14h,   6, 2Fh
						    ; DATA XREF: ROM:off_1033o
		db  64h,   0, 4Fh, 64h,	  0, 82h, 15h, 30h, 0Eh, 50h, 0Bh, 70h,	0Dh, 4Eh, 96h,	 0
		db  14h,   3, 2Eh, 64h,	  0, 12h,   7, 14h,   4, 2Fh, 50h,   0,	4Fh, 1Eh,   0, 82h
		db  2Fh, 50h,	0, 4Fh,0DEh,0FFh
		db  82h, 13h,0FFh, 15h,	31h,0FFh, 51h,0FEh, 71h,0FFh, 15h,0FFh
byte_140C:	db  14h,   7, 50h, 0Dh,	30h, 0Dh, 10h, 0Bh, 0Eh, 1Eh,	0, 14h,	  5, 4Eh, 28h,	 0
						    ; DATA XREF: ROM:off_1033o
		db  2Eh, 32h,	0, 14h,	  2, 0Fh, 14h,	 0, 81h, 0Fh,0ECh,0FFh,	81h, 15h, 4Eh, 2Dh
		db    0, 2Eh, 14h,   0,	14h,   2, 0Fh, 14h,   0, 81h, 0Fh,0ECh,0FFh, 81h, 15h, 11h
		db 0FEh, 31h,0FEh, 51h,0FEh, 15h,0FFh
byte_1443:	db  19h,   7, 50h, 0Ch,	30h, 0Ch, 10h, 0Ch, 4Eh, 78h,	0, 2Eh,0AAh,   0, 0Eh,0DCh
						    ; DATA XREF: ROM:off_1033o
		db    0, 14h,	4, 4Fh,0F6h,0FFh, 2Fh,0F6h,0FFh, 0Fh,0F6h,0FFh,	82h, 15h, 14h,	 5
		db  14h,   3, 4Fh,   3,	  0, 2Fh,   4,	 0, 0Fh,   6,	0, 82h,	15h, 4Fh,0F7h,0FFh
		db  2Fh,0F4h,0FFh, 0Fh,0EEh,0FFh, 15h, 14h,   3, 14h,	5, 4Fh,	0Ah,   0, 2Fh, 0Fh
		db    0, 0Fh, 14h,   0,	82h, 15h, 4Fh,0CEh,0FFh, 2Fh,0B5h,0FFh,	0Fh, 9Ch,0FFh, 51h
		db 0FEh, 31h,0FEh, 11h,0FEh, 15h,0FFh
byte_149A:	db  19h,   7, 10h, 0Eh,	30h, 0Eh, 50h, 0Eh, 70h, 0Fh, 12h,   7,	0Eh, 64h,   0, 2Eh
						    ; DATA XREF: ROM:off_1033o
		db  82h,   0, 4Eh, 96h,	  0, 82h, 14h,	 6, 0Fh,0A0h,	0, 2Fh,	96h,   0, 4Fh, 8Ch
		db    0, 82h, 15h, 10h,	0Fh, 30h, 0Fh, 50h, 0Fh, 0Eh,0C8h,   0,	2Eh,0E6h,   0, 14h
		db    6, 4Eh, 32h,   2,	12h,   5, 14h,	 4, 0Fh,0ECh,0FFh, 2Fh,	14h,   0, 82h, 15h
		db  4Eh, 64h,	3, 12h,	  6, 14h,   4, 2Fh,0ECh,0FFh, 0Fh, 14h,	  0, 82h, 15h, 15h
		db  12h,   4, 14h,   6,	4Eh,   0,   1, 14h,   3, 0Fh,0F6h,0FFh,	2Fh, 0Ah,   0, 82h
		db  15h, 4Eh,0C8h,   1,	14h,   3, 2Fh,0ECh,0FFh, 0Fh, 14h,   0,	82h, 15h, 11h,0FEh
		db  31h,0FEh, 51h,0FEh,	71h,0FEh, 15h,0FFh
byte_1512:	db  19h,   7, 10h, 0Eh,	30h, 0Eh, 50h, 0Eh, 0Eh, 64h,	0, 2Eh,	78h,   0, 4Eh, 8Ch
						    ; DATA XREF: ROM:off_1033o
		db    0, 14h,	5, 0Fh,	64h,   0, 2Fh, 78h,   0, 4Fh, 8Ch,   0,	85h, 15h, 14h,	 5
		db  0Fh, 9Ch,0FFh, 2Fh,	88h,0FFh, 4Fh, 74h,0FFh, 85h, 15h, 14h,	  4, 14h,   7, 0Fh
		db  96h,   0, 2Fh, 7Dh,	  0, 4Fh, 91h,	 0, 83h, 0Fh, 74h,0FFh,	2Fh, 88h,0FFh, 4Fh
		db  74h,0FFh, 83h, 15h,	0Fh, 46h,   0, 2Fh,0DDh,0FFh, 4Fh,0DDh,0FFh, 11h,0FEh, 31h
		db 0FEh, 51h,0FEh, 15h,0FFh
byte_1567:	db  19h,   3, 30h, 0Eh,	50h, 0Eh, 2Eh, 64h,   0, 4Eh, 96h,   0,	14h, 0Ah, 2Fh, 64h
						    ; DATA XREF: ROM:off_1033o
		db    0, 4Fh, 64h,   0,	82h, 15h, 70h, 0Fh, 14h, 0Ah, 2Fh, 64h,	  0, 4Fh, 64h,	 0
		db  12h,   3, 14h,   3,	2Fh,0ECh,0FFh, 4Fh, 14h,   0, 13h,   1,	83h, 15h, 31h,0FFh
		db  51h,0FFh, 71h,0FFh,	15h,0FFh
byte_159D:	db  28h,   7, 10h, 0Fh,	30h, 0Fh, 50h, 0Fh, 0Eh,0A0h,	0, 2Eh,0C8h,   0, 4Eh, 78h
						    ; DATA XREF: ROM:off_1033o
		db    0, 14h, 0Ah, 0Fh,	28h,   0, 2Fh, 3Ch,   0, 4Fh, 96h,   0,	82h, 15h, 0Eh, 1Eh
		db    0, 2Eh, 46h,   0,	4Eh, 0Ah,   0, 14h, 0Ah, 0Fh, 32h,   0,	2Fh, 46h,   0, 4Fh
		db 0C8h,   0, 82h, 15h,	14h,   4, 0Eh, 50h,   0, 2Eh, 78h,   0,	4Eh, 3Ch,   0, 14h
		db  14h, 0Fh, 32h,   0,	2Fh, 46h,   0, 4Fh, 96h,   0, 82h, 15h,	11h,0FEh, 31h,0FEh
		db  51h,0FEh, 15h,0FFh
byte_15F1:	db 0FFh,   7, 10h, 0Eh,	30h, 0Eh, 50h, 0Eh, 0Eh,0C8h,	3, 2Eh,0E1h,   3, 4Eh,0FAh
						    ; DATA XREF: ROM:off_1033o
		db    3,0B2h,0FFh
; ---------------------------------------------------------------------------

loc_1604:					    ; CODE XREF: UpdateSounds+8Ap
		ld	hl, byte_10A
		ld	a, (hl)
		ld	(hl), 0
		zor	a
		jr	nz, loc_1633
		ld	hl, byte_17A7
		cp	(hl)
		ld	a, (byte_10C)
		jr	z, loc_1619
		cp	(hl)
		jr	nz, loc_1624

loc_1619:					    ; CODE XREF: ROM:1614j
		ld	hl, byte_17CC
		dec	(hl)
		jr	nz, loc_1624
		ld	(hl), 23h
		zor	a
		jr	nz, loc_1633

loc_1624:					    ; CODE XREF: ROM:1617j
						    ; ROM:161Dj
		ld	hl,  Struct_PSG4+24h
		ld	a, (hl)
		ld	(hl), 0
		zor	a
		jr	nz, loc_1633
		ld	a, (byte_10B)
		zor	a
		jr	z, loc_167B

loc_1633:					    ; CODE XREF: ROM:160Bj
						    ; ROM:1622j ...
		ld	hl, byte_10B
		ld	(hl), 0
		ld	b, a
		zadd	a, a
		ld	d, 0
		ld	e, a
		ld	hl, off_1033
		zadd	hl, de
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		ld	hl, byte_17A8
		ld	a, (de)
		inc	de
		cp	(hl)
		jr	c, loc_167B
		bit	5, b
		jr	nz, loc_1652
		ld	a, 1

loc_1652:					    ; CODE XREF: ROM:164Ej
		ld	(byte_17A8), a
		ld	a, b
		ld	(byte_17A7), a
		ld	hl, unk_17C9
		ld	(off_17B8), hl
		ld	hl,  OverrideTable+5
		ld	b, 3
		ld	a, (de)
		inc	de
		ld	c, a

loc_1667:					    ; CODE XREF: ROM:1672j
		sra	c
		jr	nc, loc_166F
		ld	(hl), 1
		jr	loc_1671
; ---------------------------------------------------------------------------

loc_166F:					    ; CODE XREF: ROM:1669j
		rlc	(hl)

loc_1671:					    ; CODE XREF: ROM:166Dj
		dec	hl
		djnz	loc_1667
		ld	a, 0FFh
		ld	(7F11h), a
		jr	loc_1689
; ---------------------------------------------------------------------------

loc_167B:					    ; CODE XREF: ROM:1631j
						    ; ROM:164Aj
		ld	a, (byte_17A7)
		zor	a
		ret	z
		ld	hl, byte_17AB
		dec	(hl)
		ret	nz
		ld	de, (word_17A9)

loc_1689:					    ; CODE XREF: ROM:1679j
						    ; ROM:169Bj ...
		ld	a, (de)
		inc	de
		cp	0FFh
		jr	z, loc_16BF
		bit	7, a
		jr	nz, loc_16B5
		cp	0Eh
		jr	nc, loc_169D
		ld	b, a
		ld	a, (de)
		inc	de
		ld	c, a
		jr	loc_1689
; ---------------------------------------------------------------------------

loc_169D:					    ; CODE XREF: ROM:1695j
		push	af
		zand	60h
		rlca
		rlca
		rlca
		ld	(byte_17AC), a
		pop	af
		zand	1Fh
		zsub	0Eh
		zadd	a, a
		zadd	a, 2Ch
		ld	(loc_16B1+1), a

loc_16B1:					    ; DATA XREF: ROM:16AEw
		ld	hl, (off_12C)
		jp	(hl)
; ---------------------------------------------------------------------------

loc_16B5:					    ; CODE XREF: ROM:1691j
		zand	7Fh ; ''
		ld	(byte_17AB), a
		ld	(word_17A9), de
		ret
; ---------------------------------------------------------------------------

loc_16BF:					    ; CODE XREF: ROM:168Dj
		ld	hl, 13Fh
		ld	b, 3

loc_16C4:					    ; CODE XREF: ROM:16CCj
		ld	a, (hl)
		cp	1
		jr	nz, loc_16CB
		rlc	(hl)

loc_16CB:					    ; CODE XREF: ROM:16C7j
		inc	hl
		djnz	loc_16C4
		ld	a, 0FFh
		ld	(7F11h), a
		xor	a
		ld	(byte_17A7), a
		ld	(byte_17A8), a
		inc	a
		ld	(byte_17CC), a
		ret
; ---------------------------------------------------------------------------

loc_16DF:					    ; DATA XREF: ROM:off_12Co
		ld	a, (byte_17AC)
		zadd	a, a
		ld	c, a
		ld	b, 0
		ld	hl, unk_17AD
		zadd	hl, bc
		ex	de, hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ex	de, hl

loc_16F0:					    ; CODE XREF: ROM:1721j
		ld	(hl), c
		inc	hl
		ld	(hl), b
		ld	h, b
		ld	l, c
		ld	a, 0Fh
		zand	l
		ld	b, a
		ld	a, (byte_17AC)
		rrca
		rrca
		rrca
		zor	80h
		zor	b
		call	loc_FDD
		jp	loc_1689
; ---------------------------------------------------------------------------

loc_1708:					    ; DATA XREF: ROM:012Eo
		ld	a, (byte_17AC)
		zadd	a, a
		ld	c, a
		ld	b, 0
		ld	hl, unk_17AD
		zadd	hl, bc
		push	hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ex	de, hl
		zadd	hl, bc
		ld	b, h
		ld	c, l
		pop	hl
		jr	loc_16F0
; ---------------------------------------------------------------------------

loc_1723:					    ; DATA XREF: ROM:0130o
		ld	a, (byte_17AC)
		ld	c, a
		ld	b, 0
		ld	hl, unk_17B3
		zadd	hl, bc
		ld	a, (de)
		inc	de

loc_172F:					    ; CODE XREF: ROM:1767j
		ld	(hl), a
		ld	c, a
		ld	a, (byte_17A7)
		cp	20h
		jr	nc, loc_1747
		ld	a, (u_FadeOutCnt)
		zadd	a, 0Fh
		ld	b, a
		ld	a, (Struct_PSG4+23h)
		zadd	a, c
		zsub	b
		jr	nc, loc_1746
		xor	a

loc_1746:					    ; CODE XREF: ROM:1743j
		ld	c, a

loc_1747:					    ; CODE XREF: ROM:1736j
		ld	a, (byte_17AC)
		rrca
		rrca
		rrca
		zor	90h
		ld	b, a
		ld	a, 0Fh
		zand	c
		zor	b
		call	loc_FD0
		jp	loc_1689
; ---------------------------------------------------------------------------

loc_175A:					    ; DATA XREF: ROM:0132o
		ld	a, (byte_17AC)
		ld	c, a
		ld	b, 0
		ld	hl, unk_17B3
		zadd	hl, bc
		ld	a, (de)
		inc	de
		zadd	a, (hl)
		jr	loc_172F
; ---------------------------------------------------------------------------

loc_1769:					    ; DATA XREF: ROM:0134o
		ld	a, (de)
		inc	de

loc_176B:					    ; CODE XREF: ROM:177Ej
		ld	(byte_17B7), a
		zand	7
		zor	0E0h
		ld	(7F11h), a
		jp	loc_1689
; ---------------------------------------------------------------------------

loc_1778:					    ; DATA XREF: ROM:0136o
		ld	hl, byte_17B7
		ld	a, (de)
		inc	de
		zadd	a, (hl)
		jr	loc_176B
; ---------------------------------------------------------------------------

loc_1780:					    ; DATA XREF: ROM:0138o
		ld	a, (de)
		inc	de
		ld	hl, (off_17B8)
		dec	hl
		ld	(hl), d
		dec	hl
		ld	(hl), e
		dec	hl
		ld	(hl), a
		ld	(off_17B8), hl
		jp	loc_1689
; ---------------------------------------------------------------------------

loc_1791:					    ; DATA XREF: ROM:013Ao
		ld	hl, (off_17B8)
		dec	(hl)
		jr	z, loc_179E
		inc	hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		jp	loc_1689
; ---------------------------------------------------------------------------

loc_179E:					    ; CODE XREF: ROM:1795j
		inc	hl
		inc	hl
		inc	hl
		ld	(off_17B8), hl
		jp	loc_1689
; ---------------------------------------------------------------------------
byte_17A7:	db 0				    ; DATA XREF: ROM:160Do
						    ; ROM:1656w ...
byte_17A8:	db 0				    ; DATA XREF: ROM:1644o
						    ; ROM:loc_1652w ...
word_17A9:	dw 0				    ; DATA XREF: ROM:1685r
						    ; ROM:16BAw
byte_17AB:	db 0				    ; DATA XREF: ROM:1680o
						    ; ROM:16B7w
byte_17AC:	db 0				    ; DATA XREF: ROM:16A3w
						    ; ROM:loc_16DFr ...
unk_17AD:	db    0				    ; DATA XREF: ROM:16E6o
						    ; ROM:170Fo
		db    0
		db    0
		db    0
		db    0
		db    0
unk_17B3:	db    0				    ; DATA XREF: ROM:1729o
						    ; ROM:1760o
		db    0
		db    0
		db    0
byte_17B7:	db 0				    ; DATA XREF: ROM:loc_176Bw
						    ; ROM:loc_1778o
off_17B8:	dw unk_17C9			    ; DATA XREF: ROM:165Cw
						    ; ROM:1782r ...
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
unk_17C9:	db    0				    ; DATA XREF: ROM:1659o
						    ; ROM:off_17B8o
		db    0
		db    0
byte_17CC:	db 0				    ; DATA XREF: ROM:loc_1619o
						    ; ROM:16DBw
IdleBGM:	db 0FFh				    ; DATA XREF: StopBGM+10o
; Channels Table
		dw    1Eh,   1Eh,   1Bh,   27h,	  27h,	 27h,	38h,   1Eh,   1Eh,   1Eh ; channels
; Voices Table
		dw    38h,   38h,   3Dh		    ; voices
; Channel track: FM 3
		db    0, 87h			    ; Flag 00h:	Set tempo
		db  19h				    ; Flag 19h:	Reset FM3 Special Mode
; Channel Tracks: FM1, FM2, FM4, FM5, FM6
		db    1,   0			    ; Flag 01h:	Load voice
		db  1Ah				    ; Flag 1Ah:	Pan LR
		db  13h, 2Fh,	0		    ; Flag 13h:	Call subroutine
		db  12h, 38h,	0		    ; Flag 12h:	Jump
; Channel Tracks: PSG1-PSG3
		db    2,   0			    ; Flag 02h:	Load voice (PSG)
		db  13h, 2Fh,	0		    ; Flag 13h:	Call subroutine
		db  12h, 38h,	0		    ; Flag 12h:	Jump
; Subroutine 002Fh
		db    3,   0			    ; Flag 03h:	Set volume
		db  17h,   0			    ; Flag 17h:
		db  15h,   0			    ; Flag 15h:
		db  16h,   0			    ; Flag 16h:
		db  14h				    ; Flag 14h:	Return
; PSG 4	Track, Routine 0038h
		db 0A0h,0FFh
		db  12h, 38h,	0		    ; Flag 12h:	Jump
; FM Voice
		db    0,   0,	0,   0		    ; 0
		db 0FFh,0FFh,0FFh,0FFh		    ; 4
		db  1Fh, 1Fh, 1Fh, 1Fh		    ; 8
		db    0,   0,	0,   0		    ; 0Ch
		db    0,   0,	0,   0		    ; 10h
		db  0Fh, 0Fh, 0Fh, 0Fh		    ; 14h
		db    0
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db 0FFh
		db  14h
		db    2
		db  0Fh
		db  14h
		db    0
		db  81h	; Å
		db  0Fh
		db 0ECh	; Ï
		db 0FFh
		db  81h	; Å
		db  15h
		db  11h
		db 0FEh	; ˛
		db  31h	; 1
		db 0FEh	; ˛
		db  51h	; Q
		db 0FEh	; ˛
		db  15h
		db 0FFh
		db  19h
		db    7
		db  50h	; P
		db  0Ch
		db  30h	; 0
		db  0Ch
		db  10h
		db  0Ch
		db  4Eh	; N
		db  78h	; x
		db    0
		db  2Eh	; .
		db 0AAh	; ™
		db    0
		db  0Eh
		db 0DCh	; ‹
		db    0
		db  14h
		db    4
		db  4Fh	; O
		db 0F6h	; ˆ
		db 0FFh
		db  2Fh	; /
		db 0F6h	; ˆ
		db 0FFh
		db  0Fh
		db 0F6h	; ˆ
		db 0FFh
		db  82h	; Ç
		db  15h
		db  14h
		db    5
		db  14h
		db    3
		db  4Fh	; O
		db    3
		db    0
		db  2Fh	; /
		db    4
		db    0
		db  0Fh
		db    6
		db    0
		db  82h	; Ç
		db  15h
		db  4Fh	; O
		db 0F7h	; ˜
		db 0FFh
		db  2Fh	; /
		db 0F4h	; Ù
		db 0FFh
		db  0Fh
		db 0EEh	; Ó
		db 0FFh
		db  15h
		db  14h
		db    3
		db  14h
		db    5
		db  4Fh	; O
		db  0Ah
		db    0
		db  2Fh	; /
		db  0Fh
		db    0
		db  0Fh
		db  14h
		db    0
		db  82h	; Ç
		db  15h
		db  4Fh	; O
		db 0CEh	; Œ
		db 0FFh
		db  2Fh	; /
		db 0B5h	; µ
		db 0FFh
		db  0Fh
		db  9Ch	; ú
		db 0FFh
		db  51h	; Q
		db 0FEh	; ˛
		db  31h	; 1
		db 0FEh	; ˛
		db  11h
		db 0FEh	; ˛
		db  15h
		db 0FFh
		db  19h
		db    7
		db  10h
		db  0Eh
		db  30h	; 0
		db  0Eh
		db  50h	; P
		db  0Eh
		db  70h	; p
		db  0Fh
		db  12h
		db    7
		db  0Eh
		db  64h	; d
		db    0
		db  2Eh	; .
		db  82h	; Ç
		db    0
		db  4Eh	; N
		db  96h	; ñ
		db    0
		db  82h	; Ç
		db  14h
		db    6
		db  0Fh
		db 0A0h	; †
		db    0
		db  2Fh	; /
		db  96h	; ñ
		db    0
		db  4Fh	; O
		db  8Ch	; å
		db    0
		db  82h	; Ç
		db  15h
		db  10h
		db  0Fh
		db  30h	; 0
		db  0Fh
		db  50h	; P
		db  0Fh
		db  0Eh
		db 0C8h	; »
		db    0
		db  2Eh	; .
		db 0E6h	; Ê
		db    0
		db  14h
		db    6
		db  4Eh	; N
		db  32h	; 2
		db    2
		db  12h
		db    5
		db  14h
		db    4
		db  0Fh
		db 0ECh	; Ï
		db 0FFh
		db  2Fh	; /
		db  14h
		db    0
		db  82h	; Ç
		db  15h
		db  4Eh	; N
		db  64h	; d
		db    3
		db  12h
		db    6
		db  14h
		db    4
		db  2Fh	; /
		db 0ECh	; Ï
		db 0FFh
		db  0Fh
		db  14h
		db    0
		db  82h	; Ç
		db  15h
		db  15h
		db  12h
		db    4
		db  14h
		db    6
		db  4Eh	; N
		db    0
		db    1
		db  14h
		db    3
		db  0Fh
		db 0F6h	; ˆ
		db 0FFh
		db  2Fh	; /
		db  0Ah
		db    0
		db  82h	; Ç
		db  15h
		db  4Eh	; N
		db 0C8h	; »
		db    1
		db  14h
		db    3
		db  2Fh	; /
		db 0ECh	; Ï
		db 0FFh
		db  0Fh
		db  14h
		db    0
		db  82h	; Ç
		db  15h
		db  11h
		db 0FEh	; ˛
		db  31h	; 1
		db 0FEh	; ˛
		db  51h	; Q
		db 0FEh	; ˛
		db  71h	; q
		db 0FEh	; ˛
		db  15h
		db 0FFh
		db  19h
		db    7
		db  10h
		db  0Eh
		db  30h	; 0
		db  0Eh
		db  50h	; P
		db  0Eh
		db  0Eh
		db  64h	; d
		db    0
		db  2Eh	; .
		db  78h	; x
		db    0
		db  4Eh	; N
		db  8Ch	; å
		db    0
		db  14h
		db    5
		db  0Fh
		db  64h	; d
		db    0
		db  2Fh	; /
		db  78h	; x
		db    0
		db  4Fh	; O
		db  8Ch	; å
		db    0
		db  85h	; Ö
		db  15h
		db  14h
		db    5
		db  0Fh
		db  9Ch	; ú
		db 0FFh
		db  2Fh	; /
		db  88h	; à
		db 0FFh
		db  4Fh	; O
		db  74h	; t
		db 0FFh
		db  85h	; Ö
		db  15h
		db  14h
		db    4
		db  14h
		db    7
		db  0Fh
		db  96h	; ñ
		db    0
		db  2Fh	; /
		db  7Dh	; }
		db    0
		db  4Fh	; O
		db  91h	; ë
		db    0
		db  83h	; É
		db  0Fh
		db  74h	; t
		db 0FFh
		db  2Fh	; /
		db  88h	; à
		db 0FFh
		db  4Fh	; O
		db  74h	; t
		db 0FFh
		db  83h	; É
		db  15h
		db  0Fh
		db  46h	; F
		db    0
		db  2Fh	; /
		db 0DDh	; ›
		db 0FFh
		db  4Fh	; O
		db 0DDh	; ›
		db 0FFh
		db  11h
		db 0FEh	; ˛
		db  31h	; 1
		db 0FEh	; ˛
		db  51h	; Q
		db 0FEh	; ˛
		db  15h
		db 0FFh
		db  19h
		db    3
		db  30h	; 0
		db  0Eh
		db  50h	; P
		db  0Eh
		db  2Eh	; .
		db  64h	; d
		db    0
		db  4Eh	; N
		db  96h	; ñ
		db    0
		db  14h
		db  0Ah
		db  2Fh	; /
		db  64h	; d
		db    0
		db  4Fh	; O
		db  64h	; d
		db    0
		db  82h	; Ç
		db  15h
		db  70h	; p
		db  0Fh
		db  14h
		db  0Ah
		db  2Fh	; /
		db  64h	; d
		db    0
		db  4Fh	; O
		db  64h	; d
		db    0
		db  12h
		db    3
		db  14h
		db    3
		db  2Fh	; /
		db 0ECh	; Ï
		db 0FFh
		db  4Fh	; O
		db  14h
		db    0
		db  13h
		db    1
		db  83h	; É
		db  15h
		db  31h	; 1
		db 0FFh
		db  51h	; Q
		db 0FFh
		db  71h	; q
		db 0FFh
		db  15h
		db 0FFh
		db  28h	; (
		db    7
		db  10h
		db  0Fh
		db  30h	; 0
		db  0Fh
		db  50h	; P
		db  0Fh
		db  0Eh
		db 0A0h	; †
		db    0
		db  2Eh	; .
		db 0C8h	; »
		db    0
		db  4Eh	; N
		db  78h	; x
		db    0
		db  14h
		db  0Ah
		db  0Fh
		db  28h	; (
		db    0
		db  2Fh	; /
		db  3Ch	; <
		db    0
		db  4Fh	; O
		db  96h	; ñ
		db    0
		db  82h	; Ç
		db  15h
		db  0Eh
		db  1Eh
		db    0
		db  2Eh	; .
		db  46h	; F
		db    0
		db  4Eh	; N
		db  0Ah
		db    0
		db  14h
		db  0Ah
		db  0Fh
		db  32h	; 2
		db    0
		db  2Fh	; /
		db  46h	; F
		db    0
		db  4Fh	; O
		db 0C8h	; »
		db    0
		db  82h	; Ç
		db  15h
		db  14h
		db    4
		db  0Eh
		db  50h	; P
		db    0
		db  2Eh	; .
		db  78h	; x
		db    0
		db  4Eh	; N
		db  3Ch	; <
		db    0
		db  14h
		db  14h
		db  0Fh
		db  32h	; 2
		db    0
		db  2Fh	; /
		db  46h	; F
		db    0
		db  4Fh	; O
		db  96h	; ñ
		db    0
		db  82h	; Ç
		db  15h
		db  11h
		db 0FEh	; ˛
		db  31h	; 1
		db 0FEh	; ˛
		db  51h	; Q
		db 0FEh	; ˛
		db  15h
		db 0FFh
		db 0FFh
		db    7
		db  10h
		db  0Eh
		db  30h	; 0
		db  0Eh
		db  50h	; P
		db  0Eh
		db  0Eh
		db 0C8h	; »
		db    3
		db  2Eh	; .
		db 0E1h	; ·
		db    3
		db  4Eh	; N
		db 0FAh	; ˙
		db    3
		db 0B2h	; ≤
		db 0FFh
		db  21h	; !
		db  0Ah
		db    1
		db  7Eh	; ~
		db  36h	; 6
		db    0
		db 0B7h	; ∑
		db  20h
		db  26h	; &
		db  21h	; !
		db 0A7h	; ß
		db  17h
		db 0BEh	; æ
		db  3Ah	; :
		db  0Ch
		db    1
		db  28h	; (
		db    3
		db 0BEh	; æ
		db  20h
		db  0Bh
		db  21h	; !
		db 0CCh	; Ã
		db  17h
		db  35h	; 5
		db  20h
		db    5
		db  36h	; 6
		db  23h	; #
		db 0B7h	; ∑
		db  20h
		db  0Fh
		db  21h	; !
		db 0C6h	; ∆
		db  0Fh
		db  7Eh	; ~
		db  36h	; 6
		db    0
		db 0B7h	; ∑
		db  20h
		db    6
		db  3Ah	; :
		db  0Bh
		db    1
		db 0B7h	; ∑
		db  28h	; (
		db  48h	; H
		db  21h	; !
		db  0Bh
		db    1
		db  36h	; 6
		db    0
		db  47h	; G
		db  87h	; á
		db  16h
		db    0
		db  5Fh	; _
		db  21h	; !
		db  33h	; 3
		db  10h
		db  19h
		db  5Eh	; ^
		db  23h	; #
		db  56h	; V
		db  21h	; !
		db 0A8h	; ®
		db  17h
		db  1Ah
		db  13h
		db 0BEh	; æ
		db  38h	; 8
		db  2Fh	; /
		db 0CBh	; À
		db  68h	; h
		db  20h
		db    2
		db  3Eh	; >
		db    1
		db  32h	; 2
		db 0A8h	; ®
		db  17h
		db  78h	; x
		db  32h	; 2
		db 0A7h	; ß
		db  17h
		db  21h	; !
		db 0C9h	; …
		db  17h
		db  22h	; "
		db 0B8h	; ∏
		db  17h
		db  21h	; !
		db  41h	; A
		db    1
		db    6
		db    3
		db  1Ah
		db  13h
		db  4Fh	; O
		db 0CBh	; À
		db  29h	; )
		db  30h	; 0
		db    4
		db  36h	; 6
		db    1
		db  18h
		db    2
		db 0CBh	; À
		db    6
		db  2Bh	; +
		db  10h
		db 0F3h	; Û
		db  3Eh	; >
		db 0FFh
		db  32h	; 2
		db  11h
		db  7Fh	; 
		db  18h
		db  0Eh
		db  3Ah	; :
		db 0A7h	; ß
		db  17h
		db 0B7h	; ∑
		db 0C8h	; »
		db  21h	; !
		db 0ABh	; ´
		db  17h
		db  35h	; 5
		db 0C0h	; ¿
		db 0EDh	; Ì
		db  5Bh	; [
		db 0A9h	; ©
		db  17h
		db  1Ah
		db  13h
		db 0FEh	; ˛
		db 0FFh
		db  28h	; (
		db  30h	; 0
		db 0CBh	; À
		db  7Fh	; 
		db  20h
		db  22h	; "
		db 0FEh	; ˛
		db  0Eh
		db  30h	; 0
		db    6
		db  47h	; G
		db  1Ah
		db  13h
		db  4Fh	; O
		db  18h
		db 0ECh	; Ï
		db 0F5h	; ı
		db 0E6h	; Ê
		db  60h	; `
		db    7
		db    7
		db    7
		db  32h	; 2
		db 0ACh	; ¨
		db  17h
		db 0F1h	; Ò
		db 0E6h	; Ê
		db  1Fh
		db 0D6h	; ÷
		db  0Eh
		db  87h	; á
		db 0C6h	; ∆
		db  2Ch	; ,
		db  32h	; 2
		db 0B2h	; ≤
		db  16h
		db  2Ah	; *
		db  2Ch	; ,
		db    1
		db 0E9h	; È
		db 0E6h	; Ê
		db  7Fh	; 
		db  32h	; 2
		db 0ABh	; ´
		db  17h
		db 0EDh	; Ì
		db  53h	; S
		db 0A9h	; ©
		db  17h
		db 0C9h	; …
		db  21h	; !
		db  3Fh	; ?
		db    1
		db    6
		db    3
		db  7Eh	; ~
		db 0FEh	; ˛
		db    1
		db  20h
		db    2
		db 0CBh	; À
		db    6
		db  23h	; #
		db  10h
		db 0F6h	; ˆ
		db  3Eh	; >
		db 0FFh
		db  32h	; 2
		db  11h
		db  7Fh	; 
		db 0AFh	; Ø
		db  32h	; 2
		db 0A7h	; ß
		db  17h
		db  32h	; 2
		db 0A8h	; ®
		db  17h
		db  3Ch	; <
		db  32h	; 2
		db 0CCh	; Ã
		db  17h
		db 0C9h	; …
		db  3Ah	; :
		db 0ACh	; ¨
		db  17h
		db  87h	; á
		db  4Fh	; O
		db    6
		db    0
		db  21h	; !
		db 0ADh	; ≠
		db  17h
		db    9
		db 0EBh	; Î
		db  4Eh	; N
		db  23h	; #
		db  46h	; F
		db  23h	; #
		db 0EBh	; Î
		db  71h	; q
		db  23h	; #
		db  70h	; p
		db  60h	; `
		db  69h	; i
		db  3Eh	; >
		db  0Fh
		db 0A5h	; •
		db  47h	; G
		db  3Ah	; :
		db 0ACh	; ¨
		db  17h
		db  0Fh
		db  0Fh
		db  0Fh
		db 0F6h	; ˆ
		db  80h	; Ä
		db 0B0h	; ∞
		db 0CDh	; Õ
		db 0DDh	; ›
		db  0Fh
		db 0C3h	; √
		db  89h	; â
		db  16h
		db  3Ah	; :
		db 0ACh	; ¨
		db  17h
		db  87h	; á
		db  4Fh	; O
		db    6
		db    0
		db  21h	; !
		db 0ADh	; ≠
		db  17h
		db    9
		db 0E5h	; Â
		db  4Eh	; N
		db  23h	; #
		db  46h	; F
		db 0EBh	; Î
		db  5Eh	; ^
		db  23h	; #
		db  56h	; V
		db  23h	; #
		db 0EBh	; Î
		db    9
		db  44h	; D
		db  4Dh	; M
		db 0E1h	; ·
		db  18h
		db 0CDh	; Õ
		db  3Ah	; :
		db 0ACh	; ¨
		db  17h
		db  4Fh	; O
		db    6
		db    0
		db  21h	; !
		db 0B3h	; ≥
		db  17h
		db    9
		db  1Ah
		db  13h
		db  77h	; w
		db  4Fh	; O
		db  3Ah	; :
		db 0A7h	; ß
		db  17h
		db 0FEh	; ˛
		db  20h
		db  30h	; 0
		db  0Fh
		db  3Ah	; :
		db 0C1h	; ¡
		db  0Ch
		db 0C6h	; ∆
		db  0Fh
		db  47h	; G
		db  3Ah	; :
		db 0C5h	; ≈
		db  0Fh
		db  81h	; Å
		db  90h	; ê
		db  30h	; 0
		db    1
		db 0AFh	; Ø
		db  4Fh	; O
		db  3Ah	; :
		db 0ACh	; ¨
		db  17h
		db  0Fh
		db  0Fh
		db  0Fh
		db 0F6h	; ˆ
		db  90h	; ê
		db  47h	; G
		db  3Eh	; >
		db  0Fh
		db 0A1h	; °
		db 0B0h	; ∞
		db 0CDh	; Õ
		db 0D0h	; –
		db  0Fh
		db 0C3h	; √
		db  89h	; â
		db  16h
		db  3Ah	; :
		db 0ACh	; ¨
		db  17h
		db  4Fh	; O
		db    6
		db    0
		db  21h	; !
		db 0B3h	; ≥
		db  17h
		db    9
		db  1Ah
		db  13h
		db  86h	; Ü
		db  18h
		db 0C6h	; ∆
		db  1Ah
		db  13h
		db  32h	; 2
		db 0B7h	; ∑
		db  17h
		db 0E6h	; Ê
		db    7
		db 0F6h	; ˆ
		db 0E0h	; ‡
		db  32h	; 2
		db  11h
		db  7Fh	; 
		db 0C3h	; √
		db  89h	; â
		db  16h
		db  21h	; !
		db 0B7h	; ∑
		db  17h
		db  1Ah
		db  13h
		db  86h	; Ü
		db  18h
		db 0EBh	; Î
		db  1Ah
		db  13h
		db  2Ah	; *
		db 0B8h	; ∏
		db  17h
		db  2Bh	; +
		db  72h	; r
		db  2Bh	; +
		db  73h	; s
		db  2Bh	; +
		db  77h	; w
		db  22h	; "
		db 0B8h	; ∏
		db  17h
		db 0C3h	; √
		db  89h	; â
		db  16h
		db  2Ah	; *
		db 0B8h	; ∏
		db  17h
		db  35h	; 5
		db  28h	; (
		db    7
		db  23h	; #
		db  5Eh	; ^
		db  23h	; #
		db  56h	; V
		db 0C3h	; √
		db  89h	; â
		db  16h
		db  23h	; #
		db  23h	; #
		db  23h	; #
		db  22h	; "
		db 0B8h	; ∏
		db  17h
		db 0C3h	; √
		db  89h	; â
		db  16h
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db 0C9h	; …
		db  17h
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db 0FFh
		db  1Eh
		db    0
		db  1Eh
		db    0
		db  1Bh
		db    0
		db  27h	; '
		db    0
		db  27h	; '
		db    0
		db  27h	; '
		db    0
		db  38h	; 8
		db    0
		db  1Eh
		db    0
		db  1Eh
		db    0
		db  1Eh
		db    0
		db  38h	; 8
		db    0
		db  38h	; 8
		db    0
		db  3Dh	; =
		db    0
		db    0
		db  87h	; á
		db  19h
		db    1
		db    0
		db  1Ah
		db  13h
		db  2Fh	; /
		db    0
		db  12h
		db  38h	; 8
		db    0
		db    2
		db    0
		db  13h
		db  2Fh	; /
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  20h
		db  30h	; 0
; end of 'ROM'

	z80prog
