//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainMenuCardMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainMenuCardMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 130
        ///
        ///uniform sampler2D texture;
        ///uniform sampler2D palette;
        ///
        ///void main(){
        ///    vec4 textureColor = texture2D(texture, gl_TexCoord[0].xy).rgba;
        ///    vec4 paletteColor = texture2D(palette, vec2(textureColor.r, textureColor.g)).rgba;
        ///    gl_FragColor = vec4(paletteColor.r, paletteColor.g, paletteColor.b, paletteColor.a);
        ///}.
        /// </summary>
        internal static string PixelFragmentShader {
            get {
                return ResourceManager.GetString("PixelFragmentShader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 130
        ///
        ///uniform sampler2D texture;
        ///uniform sampler2D palette;
        ///in int line;
        ///
        ///void main(){
        ///    vec4 textureColor = texture2D(texture, gl_TexCoord[0].xy).rgba;
        ///    vec4 paletteColor = texture2D(palette, vec2(textureColor.r, line)).rgba;
        ///    gl_FragColor = vec4(paletteColor.r, paletteColor.g, paletteColor.b, paletteColor.a);
        ///}.
        /// </summary>
        internal static string PixelFragmentShader2 {
            get {
                return ResourceManager.GetString("PixelFragmentShader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 130
        ///
        ///void main(){
        ///    gl_Position = ftransform(); 
        ///    gl_TexCoord[0] = gl_MultiTexCoord0;
        ///}.
        /// </summary>
        internal static string PixelVertexShader {
            get {
                return ResourceManager.GetString("PixelVertexShader", resourceCulture);
            }
        }
    }
}
