print "Sonic 1 Level Order Parser"
print "By Afti"
postghz1= raw_input('After GHZ1, load:')
postghz2= raw_input('After GHZ2, load:')
postghz3= raw_input('After GHZ3, load:')
postghz4= raw_input('After GHZ4, load:')
postlz1= raw_input('After LZ1, load:')
postlz2= raw_input('After LZ2, load:')
postlz3= raw_input('After LZ3, load:')
postlz4= raw_input('After LZ4 (SBZ3), load:')
postmz1= raw_input('After MZ1, load:')
postmz2= raw_input('After MZ2, load:')
postmz3= raw_input('After MZ3, load:')
postmz4= raw_input('After MZ4, load:')
postslz1= raw_input('After SLZ1, load:')
postslz2= raw_input('After SLZ2, load:')
postslz3= raw_input('After SLZ3, load:')
postslz4= raw_input('After SLZ4, load:')
postsyz1= raw_input('After SYZ1, load:')
postsyz2= raw_input('After SYZ2, load:')
postsyz3= raw_input('After SYZ3, load:')
postsyz4= raw_input('After SYZ4, load:')
postsbz1= raw_input('After SBZ1, load:')
postsbz2= raw_input('After SBZ2, load:')
postsbz3= raw_input('After SBZ3 (FZ), load:')
postsbz4= raw_input('After SBZ4, load:')
print "Copy this sequence to lvl_ord.bin."
print postghz1, postghz2, postghz3, postghz4, postlz1, postlz2, postlz3, postlz4, postmz1, postmz2, postmz3, postmz4, postslz1, postslz2, postslz3, postslz4, postsyz1, postsyz2, postsyz3, postsyz4, postsbz1, postsbz2, postsbz3, postsbz4
a=raw_input('Press any key to close.')
