

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-327F-7274-B7			    |
; |			       ESET spol. s r.o.			    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	394E406EC0FA87A4468CF4079C004AF3
; Input	CRC32 :	D7A7EE8D

; ---------------------------------------------------------------------------
; File Name   :	D:\VStudio-Programme\VC2010\SMPSPlay\SMPS_Lib\Z80Drvs\DAC\Type2\Zaxxon Motherbase 2000 32X (JU)	[!].bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 1C0Dh Loaded length: 1C0Dh

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Regular

		di
		di
		im	1
		jp	InitDriver
; ---------------------------------------------------------------------------
		db 0

; =============== S U B	R O U T	I N E =======================================


GetListOfs = 08h				; CODE XREF: DoModulation+55p
					; PlaySoundID+5Dp ...
		ld	hl, (word_1C02)	; get Pointer List Offset from 1C02/03
		ld	b, 0
		add	hl, bc
		ex	af, af'
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ex	af, af'
		ret
; End of function GetListOfs

; ---------------------------------------------------------------------------
		db 0, 0, 0

; =============== S U B	R O U T	I N E =======================================


ReadPtrTable = 18h				; CODE XREF: TrkUpdate_Proc+36p
					; TrkUpdate_Proc+52p ...
		ld	c, a
		ld	b, 0
		add	hl, bc
		add	hl, bc
		nop
		nop
		nop

ReadPtrFromHL = 20h				; CODE XREF: PlaySoundID+61p
					; PlaySoundID+10Ap ...
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ret
; End of function ReadPtrTable

; ---------------------------------------------------------------------------
		dsb 13h, 0
; ---------------------------------------------------------------------------

VInt:
		di
		push	af
		push	bc
		push	de
		push	hl
		push	ix
		push	iy
		exx
		ld	a, (byte_1C08)
		or	86h
		ld	(byte_1C08), a
	;	ld	bc, unk_1C07	; Switch to Music Bank (1C06/1C07)
	;	ld	hl, 6000h	; HL = Bank Switch Register
	;	ld	a, (bc)
	;	rlca
	;	ld	(hl), a		; lowest bit = (1C07 & 0x80)
	;	dec	bc
	;	ld	a, (bc)		; load high 8 bits from	  1C06
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
		ld	a, (byte_1C08)
		and	0FDh
		or	1
		ld	(byte_1C08), a
		call	DoSoundQueue
		ld	a, (byte_1C08)
		and	7Eh
		ld	(byte_1C08), a
		call	UpdateAll
		ld	a, (byte_1C08)
		or	82h
		ld	(byte_1C08), a
	;	ld	bc,  word_1C04+1 ; Switch to DAC Bank (1C04/1C05)
	;	ld	hl, 6000h
	;	ld	a, (bc)
	;	rlca
	;	ld	(hl), a
	;	dec	bc
	;	ld	a, (bc)
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
		ld	a, (byte_1C08)
		and	7Dh
		ld	(byte_1C08), a
		exx
		pop	iy
		pop	ix
		pop	hl
		pop	de
		pop	bc
		pop	af
		ld	b, 1
		ei
		ret
; ---------------------------------------------------------------------------

InitDriver:				; CODE XREF: RAM:0004j
		ld	sp, 2000h
		call	StopAllSound
		di
		ld	a, (byte_1C08)
		or	82h
		ld	(byte_1C08), a
	;	ld	bc,  word_1C04+1 ; Switch to DAC Bank (1C04/1C05)
	;	ld	hl, 6000h
	;	ld	a, (bc)
	;	rlca
	;	ld	(hl), a
	;	dec	bc
	;	ld	a, (bc)
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
		ld	a, (byte_1C08)
		and	7Dh
		ld	(byte_1C08), a
		ei
		jp	MainLoop

; =============== S U B	R O U T	I N E =======================================


WriteFMIorII:				; CODE XREF: SendFMFreq+Fp
					; SendFMFreq+15p ...

; FUNCTION CHUNK AT 0106 SIZE 00000002 BYTES

		bit	7, (ix+1)
		ret	nz
		bit	2, (ix+0)
		ret	nz
		add	a, (ix+1)
		bit	2, (ix+1)
		jr	nz, WriteFMIIPart
; End of function WriteFMIorII


; =============== S U B	R O U T	I N E =======================================


WriteFMI:				; CODE XREF: SendFMFreq+3Bp
					; SendFMFreq+42p ...
		ld	(4000h), a
		nop
		ld	a, c
		ld	(4001h), a
		nop
		nop
		ret
; End of function WriteFMI

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR WriteFMIorII

WriteFMIIPart:				; CODE XREF: WriteFMIorII+11j
		sub	4
; END OF FUNCTION CHUNK	FOR WriteFMIorII

; =============== S U B	R O U T	I N E =======================================


WriteFMII:				; CODE XREF: DoPause+126p
		ld	(4002h), a
		nop
		ld	a, c
		ld	(4003h), a
		nop
		nop
		ret
; End of function WriteFMII


; =============== S U B	R O U T	I N E =======================================


UpdateAll:				; CODE XREF: RAM:0079p
		call	DoPause
		call	DoTempo
		call	DoFading
		call	PlaySoundID
		call	UpdateSFXTracks
		xor	a
		ld	(byte_1C19), a	; 00 - Music Mode
		ld	ix, byte_1C40	; 1C40 - Music Track Drum
		bit	7, (ix+0)
		call	nz, DrumUpdateTrack
		ld	b, 9		; 9 Music Tracks (10 minus Drum	Track)
		ld	ix, unk_1C70	; 1C70 - Music Track FM1
		jr	TrkUpdateLoop
; End of function UpdateAll


; =============== S U B	R O U T	I N E =======================================


UpdateSFXTracks:			; CODE XREF: UpdateAll+Cp
		ld	a, 1
		ld	(byte_1C19), a	; 01 - SFX Mode
		ld	ix, unk_1E20	; 1E20 - SFX Tracks
		ld	b, 7		; 7 SFX	tracks
		call	TrkUpdateLoop
		ld	a, 80h
		ld	(byte_1C19), a	; 80 - Special SFX Mode
		ld	b, 1		; 1 special SFX	track
		ld	ix, unk_1F70	; 1F70 - Special SFX Tracks
; End of function UpdateSFXTracks


; =============== S U B	R O U T	I N E =======================================


TrkUpdateLoop:				; CODE XREF: UpdateAll+24j
					; UpdateSFXTracks+Bp ...
		push	bc
		bit	7, (ix+0)
		call	nz, UpdateTrack
		ld	de, 30h
		add	ix, de
		pop	bc
		djnz	TrkUpdateLoop
		ret
; End of function TrkUpdateLoop


; =============== S U B	R O U T	I N E =======================================


UpdateTrack:				; CODE XREF: TrkUpdateLoop+5p

; FUNCTION CHUNK AT 02D7 SIZE 00000019 BYTES
; FUNCTION CHUNK AT 0DA8 SIZE 00000073 BYTES

		bit	7, (ix+1)
		jp	nz, UpdatePSGTrk
		call	TrackTimeout
		jr	nz, loc_186
		call	TrkUpdate_Proc
		bit	4, (ix+0)
		ret	nz
		call	PrepareModulat
		call	DoPitchSlide	; also updates the frequency
		call	DoModulation
		call	SendFMFreq
		jp	DoNoteOn
; ---------------------------------------------------------------------------
		; Note:	ExecPanAnim missing

loc_186:				; CODE XREF: UpdateTrack+Aj
		bit	4, (ix+0)
		ret	nz
		; Note:	DoFMVolEnv missing
		ld	a, (ix+1Eh)
		or	a
		jr	z, loc_197
		dec	(ix+1Eh)
		jp	z, DoNoteOff

loc_197:				; CODE XREF: UpdateTrack+2Cj
		call	DoPitchSlide
		bit	6, (ix+0)
		ret	nz
		call	DoModulation
; End of function UpdateTrack


; =============== S U B	R O U T	I N E =======================================


SendFMFreq:				; CODE XREF: UpdateTrack+1Dp
		bit	2, (ix+0)
		ret	nz
		bit	0, (ix+0)
		jp	nz, loc_1BB

loc_1AE:				; CODE XREF: SendFMFreq+1Ej
		ld	a, 0A4h
		ld	c, h
		call	WriteFMIorII
		ld	a, 0A0h
		ld	c, l
		call	WriteFMIorII
		ret
; ---------------------------------------------------------------------------

loc_1BB:				; CODE XREF: SendFMFreq+9j
		ld	a, (ix+1)
		cp	2
		jr	nz, loc_1AE
		call	GetFM3FreqPtr
		ld	b, 4
		ld	hl, SpcFM3Regs

loc_1CA:				; CODE XREF: SendFMFreq+47j
		push	bc
		ld	a, (hl)
		inc	hl
		push	hl
		ex	de, hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ex	de, hl
		ld	l, (ix+0Dh)
		ld	h, (ix+0Eh)
		add	hl, bc
		push	af
		ld	c, h
		call	WriteFMI
		pop	af
		sub	4
		ld	c, l
		call	WriteFMI
		pop	hl
		pop	bc
		djnz	loc_1CA
		ret
; End of function SendFMFreq

; ---------------------------------------------------------------------------
SpcFM3Regs:	db 0ADh, 0AEh, 0ACh, 0A6h ; DATA XREF: SendFMFreq+25o

; =============== S U B	R O U T	I N E =======================================


GetFM3FreqPtr:				; CODE XREF: SendFMFreq+20p RAM:0CE4p
		ld	de, unk_1C2A
		ld	a, (byte_1C19)
		or	a
		ret	z		; Music	Mode (00) - 1C2A
		ld	de, unk_1C1A
		ret	p		; Special SFX Mode (80)	- 1C1A
		ld	de, unk_1C22
		ret			; SFX Mode (01)	- 1C22
; End of function GetFM3FreqPtr


; =============== S U B	R O U T	I N E =======================================


TrkUpdate_Proc:				; CODE XREF: UpdateTrack+Cp
					; UpdateTrack+C4Ap
		ld	e, (ix+3)
		ld	d, (ix+4)
		res	1, (ix+0)
		res	4, (ix+0)

loc_20E:				; CODE XREF: RAM:09CDj
		ld	a, (de)
		inc	de
		cp	0E0h
		jp	nc, cfHandler
		ex	af, af'
		call	DoNoteOff
		; Note:	DoPanAnimation missing
		ex	af, af'
		bit	3, (ix+0)
		jp	nz, DoRawFreqMode
		or	a
		jp	p, SetDuration	; 00-7F	- Delay
		sub	81h
		jp	p, GetNote	; 81-DF	- Note
		call	SetRest		; 80 - Rest
		jr	loc_25D
; ---------------------------------------------------------------------------

GetNote:				; CODE XREF: TrkUpdate_Proc+27j
		add	a, (ix+5)
		ld	hl, PSGFreqs
		push	af
		rst	ReadPtrTable
		pop	af
		bit	7, (ix+1)
		jr	nz, loc_257
		push	de
		ld	d, 8
		ld	e, 0Ch
		ex	af, af'
		xor	a

loc_245:				; CODE XREF: TrkUpdate_Proc+4Bj
		ex	af, af'
		sub	e
		jr	c, loc_24E
		ex	af, af'
		add	a, d
		jr	loc_245
; ---------------------------------------------------------------------------
		ex	af, af'

loc_24E:				; CODE XREF: TrkUpdate_Proc+47j
		add	a, e
		ld	hl, FMFreqs
		rst	ReadPtrTable
		ex	af, af'
		or	h
		ld	h, a
		pop	de

loc_257:				; CODE XREF: TrkUpdate_Proc+3Cj
		ld	(ix+0Dh), l
		ld	(ix+0Eh), h

loc_25D:				; CODE XREF: TrkUpdate_Proc+2Dj
		bit	5, (ix+0)
		jr	nz, loc_270
		ld	a, (de)
		or	a
		jp	p, loc_29C
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		jr	loc_2A3
; ---------------------------------------------------------------------------

loc_270:				; CODE XREF: TrkUpdate_Proc+61j
		ld	a, (de)
		inc	de
		ld	(ix+10h), a
		jr	loc_29B
; ---------------------------------------------------------------------------

DoRawFreqMode:				; CODE XREF: TrkUpdate_Proc+1Ej
		ld	h, a
		ld	a, (de)
		inc	de
		ld	l, a
		or	h
		jr	z, loc_28A
		ld	a, (ix+5)
		ld	b, 0
		or	a
		jp	p, loc_288
		dec	b

loc_288:				; CODE XREF: TrkUpdate_Proc+84j
		ld	c, a
		add	hl, bc

loc_28A:				; CODE XREF: TrkUpdate_Proc+7Cj
		ld	(ix+0Dh), l
		ld	(ix+0Eh), h
		bit	5, (ix+0)
		jr	z, loc_29B
		ld	a, (de)
		inc	de
		ld	(ix+10h), a

loc_29B:				; CODE XREF: TrkUpdate_Proc+75j
					; TrkUpdate_Proc+94j
		ld	a, (de)

loc_29C:				; CODE XREF: TrkUpdate_Proc+65j
		inc	de

SetDuration:				; CODE XREF: TrkUpdate_Proc+22j
					; DrumUpdate_Proc+9Aj
		call	TickMultiplier
		ld	(ix+0Ch), a

loc_2A3:				; CODE XREF: TrkUpdate_Proc+6Ej
					; DrumUpdate_Proc+A4j
		ld	(ix+3),	e
		ld	(ix+4),	d
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		bit	1, (ix+0)
		ret	nz
		xor	a
		ld	(ix+25h), a
		ld	(ix+22h), a
		ld	(ix+17h), a
		ld	a, (ix+1Fh)
		ld	(ix+1Eh), a
		ret
; End of function TrkUpdate_Proc


; =============== S U B	R O U T	I N E =======================================


TickMultiplier:				; CODE XREF: TrkUpdate_Proc:SetDurationp
					; RAM:cfE8_NoteStopp
		ld	b, (ix+2)
		dec	b
		ret	z
		ld	c, a

loc_2CB:				; CODE XREF: TickMultiplier+7j
		add	a, c
		djnz	loc_2CB
		ret
; End of function TickMultiplier


; =============== S U B	R O U T	I N E =======================================


TrackTimeout:				; CODE XREF: UpdateTrack+7p
					; DrumUpdateTrackp ...
		ld	a, (ix+0Bh)
		dec	a
		ld	(ix+0Bh), a
		ret
; End of function TrackTimeout

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

DoNoteOn:				; CODE XREF: UpdateTrack+20j
		ld	a, (ix+0Dh)
		or	(ix+0Eh)
		ret	z
		ld	a, (ix+0)
		and	6
		ret	nz
		ld	a, (ix+1)
		or	0F0h
		ld	c, a
		ld	a, 28h
		call	WriteFMI
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack

; =============== S U B	R O U T	I N E =======================================


DoNoteOff:				; CODE XREF: UpdateTrack+31j
					; TrkUpdate_Proc+16p ...
		ld	a, (ix+0)
		and	6
		ret	nz

SendNoteOff:				; CODE XREF: RAM:0D4Bp
		ld	c, (ix+1)
		bit	7, c
		ret	nz
; End of function DoNoteOff

; START	OF FUNCTION CHUNK FOR SilenceFMChn

FMNoteOff:				; CODE XREF: SilenceFMChn+Dj
		ld	a, 28h
		call	WriteFMI
		res	6, (ix+0)
		ret
; END OF FUNCTION CHUNK	FOR SilenceFMChn

; =============== S U B	R O U T	I N E =======================================


PrepareModulat:				; CODE XREF: UpdateTrack+14p
					; UpdateTrack+C52p
		bit	7, (ix+7)
		ret	z
		bit	1, (ix+0)
		ret	nz
		ld	e, (ix+20h)
		ld	d, (ix+21h)
		push	ix
		pop	hl
		ld	b, 0
		ld	c, 24h
		add	hl, bc
		ex	de, hl
		ldi
		ldi
		ldi
		ld	a, (hl)
		srl	a
		ld	(de), a
		xor	a
		ld	(ix+22h), a
		ld	(ix+23h), a
		ret
; End of function PrepareModulat


; =============== S U B	R O U T	I N E =======================================


DoModulation:				; CODE XREF: UpdateTrack+1Ap
					; UpdateTrack+3Cp ...
		ld	a, (ix+7)
		or	a
		ret	z
		cp	80h
		jr	nz, DoModEnv
		dec	(ix+24h)
		ret	nz
		inc	(ix+24h)
		push	hl
		ld	l, (ix+22h)
		ld	h, (ix+23h)
		dec	(ix+25h)
		jr	nz, loc_36D
		ld	e, (ix+20h)
		ld	d, (ix+21h)
		push	de
		pop	iy
		ld	a, (iy+1)
		ld	(ix+25h), a
		ld	a, (ix+26h)
		ld	c, a
		and	80h
		rlca
		neg
		ld	b, a
		add	hl, bc
		ld	(ix+22h), l
		ld	(ix+23h), h

loc_36D:				; CODE XREF: DoModulation+1Aj
		pop	bc
		add	hl, bc
		dec	(ix+27h)
		ret	nz
		ld	a, (iy+3)
		ld	(ix+27h), a
		ld	a, (ix+26h)
		neg
		ld	(ix+26h), a
		ret
; ---------------------------------------------------------------------------

DoModEnv:				; CODE XREF: DoModulation+7j
		dec	a
		ex	de, hl
		ld	c, 8
		rst	GetListOfs	; get List 4 (Modulation Pointers)
		rst	ReadPtrTable
		jr	loc_38D
; ---------------------------------------------------------------------------

loc_38A:				; CODE XREF: DoModulation+82j
					; DoModulation+85j
		ld	(ix+25h), a

loc_38D:				; CODE XREF: DoModulation+57j
					; DoModulation+95j
		push	hl
		ld	c, (ix+25h)
		ld	b, 0
		add	hl, bc
		ld	a, (hl)
		pop	hl
		bit	7, a
		jp	z, ModEnv_Positive
		cp	82h
		jr	z, ModEnv_Jump2Idx
		cp	80h
		jr	z, ModEnv_Reset
		cp	84h
		jr	z, ModEnv_ChgMult
		ld	h, 0FFh
		jr	nc, ModEnv_Next
		set	6, (ix+0)
		pop	hl
		ret
; ---------------------------------------------------------------------------

ModEnv_Jump2Idx:			; CODE XREF: DoModulation+6Cj
		inc	bc
		ld	a, (bc)
		jr	loc_38A
; ---------------------------------------------------------------------------

ModEnv_Reset:				; CODE XREF: DoModulation+70j
		xor	a
		jr	loc_38A
; ---------------------------------------------------------------------------

ModEnv_ChgMult:				; CODE XREF: DoModulation+74j
		inc	bc
		ld	a, (bc)
		add	a, (ix+22h)
		ld	(ix+22h), a
		inc	(ix+25h)
		inc	(ix+25h)
		jr	loc_38D
; ---------------------------------------------------------------------------

ModEnv_Positive:			; CODE XREF: DoModulation+67j
		ld	h, 0

ModEnv_Next:				; CODE XREF: DoModulation+78j
		ld	l, a
		ld	b, (ix+22h)
		inc	b
		ex	de, hl

loc_3D0:				; CODE XREF: DoModulation+A0j
		add	hl, de
		djnz	loc_3D0
		inc	(ix+25h)
		ret
; End of function DoModulation


; =============== S U B	R O U T	I N E =======================================


DoPitchSlide:				; CODE XREF: UpdateTrack+17p
					; UpdateTrack:loc_197p	...
		ld	b, 0
		ld	a, (ix+10h)
		or	a
		jp	p, loc_3E1
		dec	b

loc_3E1:				; CODE XREF: DoPitchSlide+6j
		ld	h, (ix+0Eh)
		ld	l, (ix+0Dh)
		ld	c, a
		add	hl, bc
		bit	7, (ix+1)
		jr	nz, loc_411
		ex	de, hl
		ld	a, 7
		and	d
		ld	b, a
		ld	c, e
		or	a
		ld	hl, 283h
		sbc	hl, bc
		jr	c, loc_403
		ld	hl, -57Bh
		add	hl, de
		jr	loc_411
; ---------------------------------------------------------------------------

loc_403:				; CODE XREF: DoPitchSlide+24j
		or	a
		ld	hl, 508h
		sbc	hl, bc
		jr	nc, loc_410
		ld	hl, 57Ch
		add	hl, de
		ex	de, hl

loc_410:				; CODE XREF: DoPitchSlide+32j
		ex	de, hl

loc_411:				; CODE XREF: DoPitchSlide+16j
					; DoPitchSlide+2Aj
		bit	5, (ix+0)
		ret	z
		ld	(ix+0Eh), h
		ld	(ix+0Dh), l
		ret
; End of function DoPitchSlide


; =============== S U B	R O U T	I N E =======================================


GetFMInsPtr:				; CODE XREF: SetInsFromSong+18p
		ld	hl, (word_1C37)
		ld	a, (byte_1C19)
		or	a
		jr	z, JumpToInsData
		ld	l, (ix+2Ah)
		ld	h, (ix+2Bh)
; End of function GetFMInsPtr


; =============== S U B	R O U T	I N E =======================================


JumpToInsData:				; CODE XREF: GetFMInsPtr+7j
					; SetInsFromSong+11p ...
		xor	a
		or	b
		ret	z
		ld	de, 19h

loc_432:				; CODE XREF: JumpToInsData+7j
		add	hl, de
		djnz	loc_432
		ret
; End of function JumpToInsData

; ---------------------------------------------------------------------------
FMInsOperators:	db 0B0h			; DATA XREF: SendFMInso
		db  30h, 38h, 34h, 3Ch
		db  50h, 58h, 54h, 5Ch
		db  60h, 68h, 64h, 6Ch
		db  70h, 78h, 74h, 7Ch
		db  80h, 88h, 84h, 8Ch
Volume_Ops:	db  40h, 48h, 44h, 4Ch	; DATA XREF: RefreshVolume+1o
SSGEG_Ops:	db  90h, 98h, 94h, 9Ch	; DATA XREF: SendSSGEGo

; =============== S U B	R O U T	I N E =======================================


SendFMIns:				; CODE XREF: DrumUpdate_Proc+5Fp
					; SetInsFromSong:loc_B7Ap ...
		ld	de, FMInsOperators
		ld	c, (ix+0Ah)
		ex	de, hl
		call	WriteFMPan
		call	WriteInsReg
		ld	(ix+1Bh), a
		ld	b, 14h

loc_465:				; CODE XREF: SendFMIns+15j
		call	WriteInsReg
		djnz	loc_465
		ld	(ix+1Ch), l
		ld	(ix+1Dh), h
		jp	RefreshVolume
; End of function SendFMIns


; =============== S U B	R O U T	I N E =======================================


WriteInsReg:				; CODE XREF: SendFMIns+Ap
					; SendFMIns:loc_465p
		ld	a, (de)
		inc	de
		ld	c, (hl)
		inc	hl
		call	WriteFMIorII
		ret
; End of function WriteInsReg


; =============== S U B	R O U T	I N E =======================================


PlaySoundID:				; CODE XREF: UpdateAll+9p

; FUNCTION CHUNK AT 056F SIZE 00000092 BYTES
; FUNCTION CHUNK AT 0B9D SIZE 0000009A BYTES

		ld	a, (byte_1C09)

PlaySnd_JumpIn:				; CODE XREF: RAM:0D2Fp
		bit	7, a
		jp	z, StopAllSound	; 00-7F	- Stop All
		cp	0F9h
		jp	nc, StopAllSound ; F9-FF - Stop	All
		cp	0F0h
		jp	nc, PlaySnd_Command ; F0-F8 - Special Commands
		cp	99h
		jp	nc, PlaySpcSFX	; EF - Special SFX
		cp	90h
		jp	nc, PlaySFX	; A0-EE	- SFX
		jp	PlayMusic	; 80-9F	- Music
; ---------------------------------------------------------------------------

PlaySnd_Command:			; CODE XREF: PlaySoundID+Fj
		sub	0F0h
		ld	hl, CmdPtrTable
		rst	ReadPtrTable
		xor	a
		ld	(byte_1C18), a
		jp	(hl)
; ---------------------------------------------------------------------------
CmdPtrTable:				; DATA XREF: PlaySoundID+21o
		dw FadeOutMusic, StopAllSound, SilencePSG, StopSpcSFX
; ---------------------------------------------------------------------------

StopSpcSFX:				; DATA XREF: PlaySoundID:CmdPtrTableo
		ld	ix, unk_1F70	; 1F70 - SFX Tracks
		ld	b, 2		; 2 special SFX	tracks (Note: only 1 is	updated	by the main loop)
		ld	a, 80h
		ld	(byte_1C19), a	; 80 - Special SFX Mode

loc_4B8:				; CODE XREF: PlaySoundID+4Bj
		push	bc
		bit	7, (ix+0)
		call	nz, loc_4C9
		ld	de, 30h
		add	ix, de
		pop	bc
		djnz	loc_4B8
		ret
; ---------------------------------------------------------------------------

loc_4C9:				; CODE XREF: PlaySoundID+42p
		push	hl
		push	hl
		jp	cfF2_StopTrk
; ---------------------------------------------------------------------------

PlayMusic:				; CODE XREF: PlaySoundID+1Cj
		sub	81h		; Sound	ID -> Music Index
		ret	m		; was 80 (dummy	command) - return
		push	af
		call	StopAllSound
		pop	af
		ld	c, 4
		rst	GetListOfs	; get List 2 (Music Pointers)
		rst	ReadPtrTable
		push	hl
		push	hl
		rst	ReadPtrFromHL
		ld	(word_1C37), hl
		pop	hl
		pop	iy
		ld	a, (iy+5)
		ld	(byte_1C13), a
		ld	(byte_1C14), a
		ld	de, 6
		add	hl, de
		ld	(word_1C33), hl
		ld	hl, FMInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1C40
		ld	b, (iy+2)
		ld	a, (iy+4)

loc_502:				; CODE XREF: PlaySoundID+A6j
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ldi
		ldi
		ldi
		ldi
		ld	(word_1C33), hl
		call	FinishFMTrkInit
		pop	bc
		djnz	loc_502
		ld	a, (iy+3)
		or	a
		jp	z, ClearSoundID
		ld	b, a
		ld	hl, PSGInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1D90
		ld	a, (iy+4)

loc_537:				; CODE XREF: PlaySoundID+D8j
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ld	bc, 6
		ldir
		ld	(word_1C33), hl
		call	FinishTrkInit
		pop	bc
		djnz	loc_537
; End of function PlaySoundID

; START	OF FUNCTION CHUNK FOR StopAllSound

ClearSoundID:				; CODE XREF: PlaySoundID+ACj
					; PlaySoundID+183j ...
		ld	a, 80h
		ld	(byte_1C09), a
		ret
; END OF FUNCTION CHUNK	FOR StopAllSound
; ---------------------------------------------------------------------------
FMInitBytes:	db  80h,   6		; DATA XREF: PlaySoundID+78o
					; StopAllSound+Do
		db  80h,   0
		db  80h,   1
		db  80h,   2
		db  80h,   4
		db  80h,   5
		db  80h,   6
PSGInitBytes:	db  80h, 80h		; DATA XREF: PlaySoundID+B0o
		db  80h,0A0h
		db  80h,0C0h
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR PlaySoundID

PlaySpcSFX:				; CODE XREF: PlaySoundID+14j
		sub	99h		; Sound	ID -> SFX Index
		ex	af, af'
		ld	a, 80h		; 80 - Special SFX Init	Mode
		ld	c, 2		; get List 1 (Special SFX)
		jr	loc_57E
; ---------------------------------------------------------------------------

PlaySFX:				; CODE XREF: PlaySoundID+19j
		sub	90h		; Sound	ID -> SFX Index
		ex	af, af'
		xor	a		; 00 - Normal SFX Init Mode
		ld	c, 6		; get List 3 (Normal SFX)

loc_57E:				; CODE XREF: PlaySoundID+FBj
		ld	(byte_1C19), a
		ex	af, af'
		rst	GetListOfs
		rst	ReadPtrTable
		push	hl
		rst	ReadPtrFromHL
		ld	(word_1C39), hl
		xor	a
		ld	(byte_1C15), a
		pop	hl
		push	hl
		pop	iy
		ld	a, (iy+2)
		ld	(byte_1C3B), a
		ld	de, 4
		add	hl, de
		ld	b, (iy+3)

loc_59E:				; CODE XREF: PlaySoundID+181j
		push	bc
		push	hl
		inc	hl
		ld	c, (hl)
		call	GetSFXChnPtrs
		set	2, (hl)
		push	ix
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_5B2
		pop	hl
		push	iy

loc_5B2:				; CODE XREF: PlaySoundID+132j
		pop	de
		pop	hl
		ldi
		ld	a, (de)
		cp	2
		call	z, ResetSpcFM3Mode
		ldi
		ld	a, (byte_1C3B)
		ld	(de), a
		inc	de
		ldi
		ldi
		ldi
		ldi
		call	FinishFMTrkInit
		bit	7, (ix+0)
		jr	z, loc_5E0
		ld	a, (ix+1)
		cp	(iy+1)
		jr	nz, loc_5E0
		set	2, (iy+0)

loc_5E0:				; CODE XREF: PlaySoundID+157j
					; PlaySoundID+15Fj
		push	hl
		ld	hl, (word_1C39)
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_5EE
		push	iy
		pop	ix

loc_5EE:				; CODE XREF: PlaySoundID+16Dj
		ld	(ix+2Ah), l
		ld	(ix+2Bh), h
		call	DoNoteOff
		call	DisableSSGEG
		pop	hl
		pop	bc
		djnz	loc_59E
		jp	ClearSoundID
; END OF FUNCTION CHUNK	FOR PlaySoundID

; =============== S U B	R O U T	I N E =======================================


GetSFXChnPtrs:				; CODE XREF: PlaySoundID+127p
					; PlaySoundID+733p
		bit	7, c
		jr	nz, loc_60D
		ld	a, c
		bit	2, a
		jr	z, loc_624
		dec	a
		jr	loc_624
; ---------------------------------------------------------------------------

loc_60D:				; CODE XREF: GetSFXChnPtrs+2j
		ld	a, 1Fh
		call	SilencePSGChn
		ld	a, 0FFh
		call	WritePSG
		ld	a, c
		srl	a
		srl	a
		srl	a
		srl	a
		srl	a
		add	a, 2

loc_624:				; CODE XREF: GetSFXChnPtrs+7j
					; GetSFXChnPtrs+Aj
		sub	2
		ld	(byte_1C32), a
		push	af
		ld	hl, SFXChnPtrs
		rst	ReadPtrTable
		push	hl
		pop	ix		; IX - SFX Track
		pop	af
		push	af
		ld	hl, SpcSFXChnPtrs
		rst	ReadPtrTable
		push	hl
		pop	iy		; IY - Special SFX Track
		pop	af
		ld	hl, BGMChnPtrs
		rst	ReadPtrTable	; HL - Music Track
		ret
; End of function GetSFXChnPtrs


; =============== S U B	R O U T	I N E =======================================


FinishFMTrkInit:			; CODE XREF: PlaySoundID+A2p
					; PlaySoundID+150p
		ex	af, af'
		xor	a
		ld	(de), a
		inc	de
		ld	(de), a
		inc	de
		ex	af, af'
; End of function FinishFMTrkInit


; =============== S U B	R O U T	I N E =======================================


FinishTrkInit:				; CODE XREF: PlaySoundID+D4p
					; DrumUpdate_Proc+42p ...
		ex	de, hl
		ld	(hl), 30h
		inc	hl
		ld	(hl), 0C0h
		inc	hl
		ld	(hl), 1
		ld	b, 24h

loc_652:				; CODE XREF: FinishTrkInit+Ej
		inc	hl
		ld	(hl), 0
		djnz	loc_652
		inc	hl
		ex	de, hl
		ret
; End of function FinishTrkInit

; ---------------------------------------------------------------------------
SpcSFXChnPtrs:	dw 1F70h, 1F70h, 1F70h,	1F70h, 1F70h, 1F70h, 1F70h, 1F70h
					; DATA XREF: GetSFXChnPtrs+32o
SFXChnPtrs:	dw 1E20h, 1E50h, 1E80h,	1EB0h, 1EE0h, 1F10h, 1F40h, 1F40h
					; DATA XREF: GetSFXChnPtrs+29o
BGMChnPtrs:	dw 1CD0h, 1D00h, 1D30h,	1D60h, 1D90h, 1DC0h, 1DF0h, 1DF0h
					; DATA XREF: GetSFXChnPtrs+3Ao

; =============== S U B	R O U T	I N E =======================================


DoPause:				; CODE XREF: UpdateAllp

; FUNCTION CHUNK AT 0798 SIZE 0000002F BYTES

		ld	hl, unk_1C10
		ld	a, (hl)
		or	a
		ret	z
		jp	m, UnpauseMusic
		pop	de
		dec	a
		ret	nz
		ld	(hl), 2
		jp	SilenceAll
; ---------------------------------------------------------------------------

UnpauseMusic:				; CODE XREF: DoPause+6j
		xor	a
		ld	(hl), a
		ld	a, (byte_1C0D)
		or	a
		jp	nz, StopAllSound
		ld	ix, byte_1C40
		ld	b, 7

loc_6AA:				; CODE XREF: DoPause+38j
		ld	a, (byte_1C11)
		or	a
		jr	nz, loc_6B6
		bit	7, (ix+0)
		jr	z, loc_6BD

loc_6B6:				; CODE XREF: DoPause+24j
		ld	c, (ix+0Ah)
		ex	de, hl
		call	WriteFMPan

loc_6BD:				; CODE XREF: DoPause+2Aj
		ld	de, 30h
		add	ix, de
		djnz	loc_6AA
		ld	ix, unk_1E20
		ld	b, 8

loc_6CA:				; CODE XREF: DoPause+58j
		bit	7, (ix+0)
		jr	z, loc_6DD
		bit	7, (ix+1)
		jr	nz, loc_6DD
		ld	c, (ix+0Ah)
		ex	de, hl
		call	WriteFMPan

loc_6DD:				; CODE XREF: DoPause+44j DoPause+4Aj
		ld	de, 30h
		add	ix, de
		djnz	loc_6CA
		ret
; End of function DoPause

; ---------------------------------------------------------------------------

FadeOutMusic:				; DATA XREF: PlaySoundID:CmdPtrTableo
		ld	a, 28h
		ld	(byte_1C0D), a
		ld	a, 2
		ld	(byte_1C0F), a
		ld	(byte_1C0E), a

; =============== S U B	R O U T	I N E =======================================


StopDrumPSG:				; CODE XREF: DoFading+6p
		xor	a
		ld	(byte_1C40), a
		ld	(byte_1D60), a
		ld	(byte_1DF0), a
		ld	(byte_1D90), a
		ld	(byte_1DC0), a
		jp	SilencePSG
; End of function StopDrumPSG


; =============== S U B	R O U T	I N E =======================================


DoFading:				; CODE XREF: UpdateAll+6p
		ld	hl, byte_1C0D
		ld	a, (hl)
		or	a
		ret	z
		call	m, StopDrumPSG
		res	7, (hl)
		ld	a, (byte_1C0F)
		dec	a
		jr	z, ApplyFading
		ld	(byte_1C0F), a
		ret
; ---------------------------------------------------------------------------

ApplyFading:				; CODE XREF: DoFading+Fj
		ld	a, (byte_1C0E)
		ld	(byte_1C0F), a
		ld	a, (byte_1C0D)
		dec	a
		ld	(byte_1C0D), a
		jr	z, StopAllSound
		ld	ix, byte_1C40
		ld	b, 6

loc_72F:				; CODE XREF: DoFading+4Bj
		inc	(ix+6)
		jp	p, loc_73A
		dec	(ix+6)
		jr	loc_74B
; ---------------------------------------------------------------------------

loc_73A:				; CODE XREF: DoFading+2Dj
		bit	7, (ix+0)
		jr	z, loc_74B
		bit	2, (ix+0)
		jr	nz, loc_74B
		push	bc
		call	RefreshVolume
		pop	bc

loc_74B:				; CODE XREF: DoFading+33j DoFading+39j ...
		ld	de, 30h
		add	ix, de
		djnz	loc_72F
		ret
; End of function DoFading


; =============== S U B	R O U T	I N E =======================================


StopAllSound:				; CODE XREF: RAM:00B6p	PlaySoundID+5j	...

; FUNCTION CHUNK AT 0555 SIZE 00000006 BYTES

		ld	hl, byte_1C09
		ld	de, unk_1C0A
		ld	bc, 396h
		ld	(hl), 0
		ldir
		ld	ix, FMInitBytes
		ld	b, 6

loc_766:				; CODE XREF: StopAllSound+1Fj
		push	bc
		call	SilenceFMChn
		call	DisableSSGEG
		inc	ix
		inc	ix
		pop	bc
		djnz	loc_766
		ld	b, 7
		xor	a
		ld	(byte_1C0D), a
		call	SilencePSG
		ld	c, 0
		ld	a, 2Bh
		call	WriteFMI

ResetSpcFM3Mode:			; CODE XREF: PlaySoundID+13Ep
					; DrumUpdate_Proc+66p
		xor	a
		ld	(byte_1C12), a
		ld	c, a
		ld	a, 27h
		call	WriteFMI
		jp	ClearSoundID
; End of function StopAllSound


; =============== S U B	R O U T	I N E =======================================


DisableSSGEG:				; CODE XREF: PlaySoundID+17Cp
					; StopAllSound+17p
		ld	a, 90h
		ld	c, 0
		jp	SendAllFMOps
; End of function DisableSSGEG

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR DoPause

SilenceAll:				; CODE XREF: DoPause+Ej
		call	SilencePSG
		push	bc
		push	af
		ld	b, 3
		ld	a, 0B4h
		ld	c, 0

loc_7A3:				; CODE XREF: DoPause+11Fj
		push	af
		call	WriteFMI
		pop	af
		inc	a
		djnz	loc_7A3
		ld	b, 3
		ld	a, 0B4h

loc_7AF:				; CODE XREF: DoPause+12Bj
		push	af
		call	WriteFMII
		pop	af
		inc	a
		djnz	loc_7AF
		ld	c, 0
		ld	b, 7
		ld	a, 28h

loc_7BD:				; CODE XREF: DoPause+139j
		push	af
		call	WriteFMI
		inc	c
		pop	af
		djnz	loc_7BD
		pop	af
		pop	bc
; END OF FUNCTION CHUNK	FOR DoPause

; =============== S U B	R O U T	I N E =======================================


SilencePSG:				; CODE XREF: StopDrumPSG+10j
					; StopAllSound+27p ...
		push	bc
		ld	b, 4
		ld	a, 9Fh

loc_7CC:				; CODE XREF: SilencePSG+Aj
		call	WritePSG
		add	a, 20h
		djnz	loc_7CC
		pop	bc
		jp	ClearSoundID
; End of function SilencePSG


; =============== S U B	R O U T	I N E =======================================


DoTempo:				; CODE XREF: UpdateAll+3p
		ld	a, (byte_1C14)
		ld	hl, byte_1C13
		add	a, (hl)
		ld	(hl), a
		ret	nc
		ld	hl, unk_1C4B
		ld	de, 30h
		ld	b, 0Ah

loc_7E8:				; CODE XREF: DoTempo+13j
		inc	(hl)
		add	hl, de
		djnz	loc_7E8
		ret
; End of function DoTempo


; =============== S U B	R O U T	I N E =======================================


DoSoundQueue:				; CODE XREF: RAM:006Ep
		ld	a, r
		ld	(byte_1C17), a
		ld	de, unk_1C0A
		ld	a, (de)
		bit	7, a
		ret	z
		sub	81h
		ld	c, 0
		cp	70h
		jr	nc, loc_80E
		rst	GetListOfs	; get List 0 (Sound Priorities)
		ld	c, a
		ld	b, 0
		add	hl, bc
		ld	a, (byte_1C18)
		cp	(hl)
		jr	z, loc_80E
		jr	nc, loc_818

loc_80E:				; CODE XREF: DoSoundQueue+12j
					; DoSoundQueue+1Dj
		ld	a, (de)
		ld	(byte_1C09), a
		ld	a, (hl)
		and	7Fh
		ld	(byte_1C18), a

loc_818:				; CODE XREF: DoSoundQueue+1Fj
		xor	a
		ld	(de), a
		inc	de
		ret
; End of function DoSoundQueue


; =============== S U B	R O U T	I N E =======================================


SilenceFMChn:				; CODE XREF: StopAllSound+14p
					; RAM:cfE3_SilenceTrkp

; FUNCTION CHUNK AT 02FC SIZE 0000000A BYTES

		call	SetMaxRelRate
		ld	a, 40h
		ld	c, 7Fh
		call	SendAllFMOps
		ld	c, (ix+1)
		jp	FMNoteOff
; End of function SilenceFMChn


; =============== S U B	R O U T	I N E =======================================


SetMaxRelRate:				; CODE XREF: SilenceFMChnp RAM:0B4Fp
		ld	a, 80h
		ld	c, 0FFh
; End of function SetMaxRelRate


; =============== S U B	R O U T	I N E =======================================


SendAllFMOps:				; CODE XREF: DisableSSGEG+4j
					; SilenceFMChn+7p
		ld	b, 4

loc_832:				; CODE XREF: SendAllFMOps+9j
		push	af
		call	WriteFMIorII
		pop	af
		add	a, 4
		djnz	loc_832
		ret
; End of function SendAllFMOps

; ---------------------------------------------------------------------------
PSGFreqs:	dw  3FFh, 3FFh,	3FFh, 3FFh, 3FFh, 3FFh,	3FFh, 3FFh, 3FFh, 3F7h,	3BEh, 388h
					; DATA XREF: TrkUpdate_Proc+32o
		dw  356h, 326h,	2F9h, 2CEh, 2A5h, 280h,	25Ch, 23Ah, 21Ah, 1FBh,	1DFh, 1C4h
		dw  1ABh, 193h,	17Dh, 167h, 153h, 140h,	12Eh, 11Dh, 10Dh, 0FEh,	0EFh, 0E2h
		dw  0D6h, 0C9h,	0BEh, 0B4h, 0A9h, 0A0h,	 97h,  8Fh,  87h,  7Fh,	 78h,  71h
		dw   6Bh,  65h,	 5Fh,  5Ah,  55h,  50h,	 4Bh,  47h,  43h,  40h,	 3Ch,  39h
		dw   36h,  33h,	 30h,  2Dh,  2Bh,  28h,	 26h,  24h,  22h,  20h,	 1Fh,  1Dh
		dw   1Bh,  1Ah,	 18h,  17h,  16h,  15h,	 13h,  12h,  11h,  10h,	   0,	 0
FMFreqs:	dw  284h, 2ABh,	2D3h, 2FEh, 32Dh, 35Ch,	38Fh, 3C5h, 3FFh, 43Ch,	47Ch, 4C0h
					; DATA XREF: TrkUpdate_Proc+4Fo

; =============== S U B	R O U T	I N E =======================================


DrumUpdateTrack:			; CODE XREF: UpdateAll+1Bp
		call	TrackTimeout
		call	z, DrumUpdate_Proc
		ret
; End of function DrumUpdateTrack


; =============== S U B	R O U T	I N E =======================================


DrumUpdate_Proc:			; CODE XREF: DrumUpdateTrack+3p
		ld	e, (ix+3)
		ld	d, (ix+4)

loc_909:				; CODE XREF: DrumUpdate_Proc+B4j
		ld	a, (de)
		inc	de
		cp	0E0h
		jp	nc, cfHandler_Drum
		or	a
		jp	m, loc_918
		dec	de
		ld	a, (ix+0Dh)

loc_918:				; CODE XREF: DrumUpdate_Proc+Ej
		ld	(ix+0Dh), a
		cp	80h
		jp	z, loc_99A
		push	de
		ld	hl, byte_1D60	; BGM Channel FM6
		bit	2, (hl)
		jr	nz, loc_96C
		and	0Fh
		jr	z, loc_96C
		ex	af, af'
		call	DoNoteOff
		ex	af, af'
		ld	de, FMDrumInit
		ex	de, hl
		ldi
		ldi
		ldi
		dec	a
		ld	hl, FMDrumTrkList
		rst	ReadPtrTable
		ld	bc, 6
		ldir
		call	FinishTrkInit
		ld	hl, unk_1D65
		ld	a, (ix+5)
		add	a, (hl)
		ld	(hl), a
		ld	a, (byte_1D68)
		ld	hl, FMDrumInsPtrs
		rst	ReadPtrTable
		ld	a, (byte_1D66)
		ld	e, (ix+6)
		push	de
		add	a, e
		ld	(ix+6),	a
		call	SendFMIns
		pop	de
		ld	(ix+6),	e
		call	ResetSpcFM3Mode

loc_96C:				; CODE XREF: DrumUpdate_Proc+23j
					; DrumUpdate_Proc+27j
		ld	hl, byte_1DF0
		bit	2, (hl)
		jr	nz, loc_999
		ld	a, (ix+0Dh)
		and	70h
		jr	z, loc_999
		ld	de, PSGDrumInit
		ex	de, hl
		ldi
		ldi
		ldi
		srl	a
		srl	a
		srl	a
		srl	a
		dec	a
		ld	hl, PSGDrumTrkList
		rst	ReadPtrTable
		ld	bc, 6
		ldir
		call	FinishTrkInit

loc_999:				; CODE XREF: DrumUpdate_Proc+6Ej
					; DrumUpdate_Proc+75j
		pop	de

loc_99A:				; CODE XREF: DrumUpdate_Proc+1Aj
		ld	a, (de)
		inc	de
		or	a
		jp	p, SetDuration
		dec	de
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		jp	loc_2A3
; ---------------------------------------------------------------------------
FMDrumInit:				; DATA XREF: DrumUpdate_Proc+2Eo
		db  80h,   6,	1
PSGDrumInit:				; DATA XREF: DrumUpdate_Proc+77o
		db  80h,0C0h,	1
; ---------------------------------------------------------------------------

cfHandler_Drum:				; CODE XREF: DrumUpdate_Proc+Aj
		ld	hl, cfReturn_Drum
		jp	loc_9C3
; ---------------------------------------------------------------------------

cfReturn_Drum:				; DATA XREF: DrumUpdate_Proc:cfHandler_Drumo
		inc	de
		jp	loc_909
; ---------------------------------------------------------------------------
PSGDrumTrkList:				; DATA XREF: DrumUpdate_Proc+8Ao
		dw 0
FMDrumTrkList:				; DATA XREF: DrumUpdate_Proc+39o
		dw 0
FMDrumInsPtrs:				; DATA XREF: DrumUpdate_Proc+50o
		dw 0
; ---------------------------------------------------------------------------

cfHandler:				; CODE XREF: TrkUpdate_Proc+12j
		ld	hl, cfReturn

loc_9C3:				; CODE XREF: DrumUpdate_Proc+B0j
		push	hl
		sub	0E0h
		ld	hl, cfPtrTable
		rst	ReadPtrTable
		ld	a, (de)
		jp	(hl)
; End of function DrumUpdate_Proc

; ---------------------------------------------------------------------------

cfReturn:				; DATA XREF: DrumUpdate_Proc:cfHandlero
		inc	de
		jp	loc_20E
; ---------------------------------------------------------------------------
cfPtrTable:	dw cfE0_Pan, cfE1_Detune, cfE2_SetComm,	cfE3_SilenceTrk
					; DATA XREF: DrumUpdate_Proc+C3o
		dw cfE4_PanAnim, cfE5_ChgPFMVol, cfE6_ChgFMVol,	cfE7_Hold
		dw cfE8_NoteStop, cfE9_SetLFO, cfEA_PlayDAC, cfEB_LoopExit
		dw cfEC_ChgPSGVol, cfED_FMChnWrite, cfEE_FM1Write, cfEF_SetIns
		dw cfF0_ModSetup, cfF1_ModTypePFM, cfF2_StopTrk, cfF3_PSGNoise
		dw cfF4_ModType, cfF5_SetPSGIns, cfF6_GoTo, cfF7_Loop
		dw cfF8_GoSub, cfF9_Return, cfFA_TickMult, cfFB_ChgTransp
		dw cfFC_PitchSlide, cfFD_RawFrqMode, cfFE_SpcFM3Mode, cfMetaCoordFlag
cfMetaPtrTable:	dw cf00_SetTempo, cf01_PlaySnd,	cf02_MusPause, cf03_CopyMem
					; DATA XREF: RAM:cfMetaCoordFlago
		dw cf04_TickMulAll, cf05_SSGEG,	UpdatePSGTrk
; ---------------------------------------------------------------------------
; EA bb	dd - Play DAC sound dd (and set	DAC bank to index bb from Bank Table)

cfEA_PlayDAC:				; DATA XREF: RAM:cfPtrTableo
		ld	bc, 0
		push	af
		and	80h
		or	a
		jr	nz, cfEA_pdac_bank
		ld	a, (byte_1C3C)	; first	byte < 80 - BC = 0000 (making Bank xxx0)
		or	a
		jr	z, loc_A42
		ld	a, (byte_1C08)
		and	8
		jr	z, loc_A42
		pop	af
		inc	de
		ret
; ---------------------------------------------------------------------------

cfEA_pdac_bank:				; CODE XREF: RAM:0A25j
		ld	a, (byte_1C08)	; first	byte >=	80 - BC	= 0F00
		or	8
		ld	(byte_1C08), a
		ld	bc, 0F00h	; make Bank value xxxF (only high 9 bits are used though)

loc_A42:				; CODE XREF: RAM:0A2Bj	RAM:0A32j
		ld	(loc_A4F+1), bc
		pop	af
		push	af
		and	7Fh
		ld	hl, DACBankTbl	; 1B80 - DAC Bank Table
		rst	ReadPtrTable
		pop	af

loc_A4F:				; DATA XREF: RAM:loc_A42w
		ld	bc, 0
		add	hl, bc
		ld	(word_1C04), hl	; set DAC Bank
		inc	de
		ld	a, (de)
		ld	(byte_1C3C), a	; play DAC sound
		ret
; ---------------------------------------------------------------------------

cfE0_Pan:				; DATA XREF: RAM:cfPtrTableo
		ld	c, 3Fh

loc_A5E:				; CODE XREF: RAM:0A9Ej
		ld	a, (ix+0Ah)
		and	c
		ld	c, a
		ex	de, hl
		ld	a, (hl)
		bit	0, a
		jp	nz, loc_A84
		or	c
		ld	(ix+0Ah), a
		ld	c, a

; =============== S U B	R O U T	I N E =======================================


WriteFMPan:				; CODE XREF: SendFMIns+7p DoPause+30p	...
		ld	a, (ix+1)
		cp	6
		jr	nz, loc_A7D
		ld	a, (byte_1C08)
		and	10h
		jr	nz, loc_A82

loc_A7D:				; CODE XREF: WriteFMPan+5j RAM:0A93j
		ld	a, 0B4h
		call	WriteFMIorII

loc_A82:				; CODE XREF: WriteFMPan+Cj
		ex	de, hl
		ret
; End of function WriteFMPan

; ---------------------------------------------------------------------------

loc_A84:				; CODE XREF: RAM:0A67j
		and	0C0h
		or	c
		ld	(ix+0Ah), a
		ld	c, a
		ld	a, (byte_1C08)
		or	10h
		ld	(byte_1C08), a
		jr	loc_A7D
; ---------------------------------------------------------------------------

cfE9_SetLFO:				; DATA XREF: RAM:cfPtrTableo
		ld	c, a
		ld	a, 22h
		call	WriteFMI
		inc	de
		ld	c, 0C0h
		jr	loc_A5E
; ---------------------------------------------------------------------------

cfE1_Detune:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+10h), a
		ret
; ---------------------------------------------------------------------------

cfE2_SetComm:				; DATA XREF: RAM:cfPtrTableo
		ld	(byte_1C16), a
		ret
; ---------------------------------------------------------------------------

cfE3_SilenceTrk:			; DATA XREF: RAM:cfPtrTableo
		call	SilenceFMChn
		jp	cfF2_StopTrk
; ---------------------------------------------------------------------------

cfE4_PanAnim:				; DATA XREF: RAM:cfPtrTableo
		push	ix
		pop	hl
		ld	bc, 11h
		add	hl, bc
		ex	de, hl
		ld	bc, 5
		ldir
		ld	a, 1
		ld	(de), a
		ex	de, hl
		dec	de
		ret
; ---------------------------------------------------------------------------

cfE5_ChgPFMVol:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, (ix+6)
		ld	(ix+6),	a
		ld	a, (de)

cfE6_ChgFMVol:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	nz
		add	a, (ix+6)
		ld	(ix+6),	a

; =============== S U B	R O U T	I N E =======================================


RefreshVolume:				; CODE XREF: SendFMIns+1Dj
					; DoFading+42p
		push	de
		ld	de, Volume_Ops
		ld	l, (ix+1Ch)
		ld	h, (ix+1Dh)
		ld	b, 4

loc_AE0:				; CODE XREF: RefreshVolume+1Dj
		ld	a, (hl)
		or	a
		jp	p, loc_AE8
		add	a, (ix+6)

loc_AE8:				; CODE XREF: RefreshVolume+Ej
		and	7Fh
		ld	c, a
		ld	a, (de)
		call	WriteFMIorII
		inc	de
		inc	hl
		djnz	loc_AE0
		pop	de
		ret
; End of function RefreshVolume

; ---------------------------------------------------------------------------

cfE7_Hold:				; DATA XREF: RAM:cfPtrTableo
		set	1, (ix+0)
		dec	de
		ret
; ---------------------------------------------------------------------------

cfE8_NoteStop:				; DATA XREF: RAM:cfPtrTableo
		call	TickMultiplier
		ld	(ix+1Eh), a
		ld	(ix+1Fh), a
		ret
; ---------------------------------------------------------------------------

cfEB_LoopExit:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, 28h
		ld	c, a
		ld	b, 0
		push	ix
		pop	hl
		add	hl, bc
		ld	a, (hl)
		dec	a
		jp	z, loc_B16
		inc	de
		ret
; ---------------------------------------------------------------------------

loc_B16:				; CODE XREF: RAM:0B11j
		xor	a
		ld	(hl), a
		jp	cfF6_GoTo
; ---------------------------------------------------------------------------

cfEC_ChgPSGVol:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	z
		res	4, (ix+0)
		dec	(ix+17h)
		add	a, (ix+6)
		cp	0Fh
		jp	c, loc_B31
		ld	a, 0Fh

loc_B31:				; CODE XREF: RAM:0B2Cj
		ld	(ix+6),	a
		ret
; ---------------------------------------------------------------------------

cfED_FMChnWrite:			; DATA XREF: RAM:cfPtrTableo
		call	ReadFMCommand
		call	WriteFMIorII
		ret
; ---------------------------------------------------------------------------

cfEE_FM1Write:				; DATA XREF: RAM:cfPtrTableo
		call	ReadFMCommand
		call	WriteFMI
		ret

; =============== S U B	R O U T	I N E =======================================


ReadFMCommand:				; CODE XREF: RAM:cfED_FMChnWritep
					; RAM:cfEE_FM1Writep
		ex	de, hl
		ld	a, (hl)
		inc	hl
		ld	c, (hl)
		ex	de, hl
		ret
; End of function ReadFMCommand

; ---------------------------------------------------------------------------

cfEF_SetIns:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		jr	nz, loc_B7F
		call	SetMaxRelRate
		ld	a, (de)
		ld	(ix+8),	a
		or	a
		jp	p, loc_B75
		inc	de
		ld	a, (de)
		ld	(ix+0Fh), a

; =============== S U B	R O U T	I N E =======================================


SetInsFromSong:				; CODE XREF: PlaySoundID+789p
		push	de
		ld	a, (ix+0Fh)
		sub	81h
		ld	c, 4
		rst	GetListOfs	; get List 2 (Music Pointers)
		rst	ReadPtrTable
		rst	ReadPtrFromHL
		ld	a, (ix+8)
		and	7Fh
		ld	b, a
		call	JumpToInsData
		jr	loc_B7A
; ---------------------------------------------------------------------------

loc_B75:				; CODE XREF: RAM:0B57j
		push	de
		ld	b, a
		call	GetFMInsPtr

loc_B7A:				; CODE XREF: SetInsFromSong+14j
		call	SendFMIns
		pop	de
		ret
; End of function SetInsFromSong

; ---------------------------------------------------------------------------

loc_B7F:				; CODE XREF: RAM:0B4Dj
		or	a
		ret	p
		inc	de
		ret
; ---------------------------------------------------------------------------

cfF0_ModSetup:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+20h), e
		ld	(ix+21h), d
		ld	(ix+7),	80h
		inc	de
		inc	de
		inc	de
		ret
; ---------------------------------------------------------------------------

cfF1_ModTypePFM:			; DATA XREF: RAM:cfPtrTableo
		inc	de
		bit	7, (ix+1)
		jr	nz, cfF4_ModType
		ld	a, (de)

cfF4_ModType:				; CODE XREF: RAM:0B96j
					; DATA XREF: RAM:cfPtrTableo
		ld	(ix+7),	a
		ret
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR PlaySoundID

cfF2_StopTrk:				; CODE XREF: PlaySoundID+50j RAM:0AABj
					; DATA XREF: ...
		res	7, (ix+0)
		ld	a, 1Fh
		ld	(byte_1C15), a
		call	DoNoteOff
		ld	c, (ix+1)
		push	ix
		call	GetSFXChnPtrs
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_C20
		xor	a
		ld	(byte_1C18), a
		bit	7, (iy+0)
		jr	z, loc_BD3
		ld	a, (ix+1)
		cp	(iy+1)
		jr	nz, loc_BD3
		push	iy
		ld	l, (iy+2Ah)
		ld	h, (iy+2Bh)
		jr	loc_BD7
; ---------------------------------------------------------------------------

loc_BD3:				; CODE XREF: PlaySoundID+744j
					; PlaySoundID+74Cj
		push	hl
		ld	hl, (word_1C37)

loc_BD7:				; CODE XREF: PlaySoundID+756j
		pop	ix
		res	2, (ix+0)
		bit	7, (ix+1)
		jr	nz, loc_C25
		bit	7, (ix+0)
		jr	z, loc_C20
		ld	a, 2
		cp	(ix+1)
		jr	nz, loc_BFD
		ld	a, 4Fh
		bit	0, (ix+0)
		jr	nz, loc_BFA
		and	0Fh

loc_BFA:				; CODE XREF: PlaySoundID+77Bj
		call	SendFM3SpcMode

loc_BFD:				; CODE XREF: PlaySoundID+773j
		ld	a, (ix+8)
		or	a
		jp	p, loc_C09
		call	SetInsFromSong
		jr	loc_C1D
; ---------------------------------------------------------------------------

loc_C09:				; CODE XREF: PlaySoundID+786j
		ld	b, a
		call	JumpToInsData
		call	SendFMIns
		ld	a, (ix+18h)
		or	a
		jp	p, loc_C20
		ld	e, (ix+19h)
		ld	d, (ix+1Ah)

loc_C1D:				; CODE XREF: PlaySoundID+78Cj
		call	SendSSGEG

loc_C20:				; CODE XREF: PlaySoundID+73Aj
					; PlaySoundID+76Cj ...
		pop	ix
		pop	hl
		pop	hl
		ret
; ---------------------------------------------------------------------------

loc_C25:				; CODE XREF: PlaySoundID+766j
		bit	0, (ix+0)
		jr	z, loc_C20
		ld	a, (ix+1Ah)
		or	a
		jp	p, loc_C35
		call	WritePSG

loc_C35:				; CODE XREF: PlaySoundID+7B4j
		jr	loc_C20
; END OF FUNCTION CHUNK	FOR PlaySoundID
; ---------------------------------------------------------------------------

cfF3_PSGNoise:				; DATA XREF: RAM:cfPtrTableo
		bit	2, (ix+1)
		ret	nz
		ld	a, 0DFh
		call	WritePSG
		ld	a, (de)
		ld	(ix+1Ah), a
		set	0, (ix+0)
		or	a
		jr	nz, loc_C52
		res	0, (ix+0)
		ld	a, 0FFh

loc_C52:				; CODE XREF: RAM:0C4Aj
		call	WritePSG
		ret
; ---------------------------------------------------------------------------

cfF5_SetPSGIns:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	z
		ld	(ix+8),	a
		ret
; ---------------------------------------------------------------------------

cfF6_GoTo:				; CODE XREF: RAM:0B18j	RAM:0C77j
					; DATA XREF: ...
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		dec	de
		ret
; ---------------------------------------------------------------------------

cfF7_Loop:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, 28h
		ld	c, a
		ld	b, 0
		push	ix
		pop	hl
		add	hl, bc
		ld	a, (hl)
		or	a
		jr	nz, loc_C75
		ld	a, (de)
		ld	(hl), a

loc_C75:				; CODE XREF: RAM:0C71j
		inc	de
		dec	(hl)
		jp	nz, cfF6_GoTo
		inc	de
		ret
; ---------------------------------------------------------------------------

cfF8_GoSub:				; DATA XREF: RAM:cfPtrTableo
		ld	c, a
		inc	de
		ld	a, (de)
		ld	b, a
		push	bc
		push	ix
		pop	hl
		dec	(ix+9)
		ld	c, (ix+9)
		dec	(ix+9)
		ld	b, 0
		add	hl, bc
		ld	(hl), d
		dec	hl
		ld	(hl), e
		pop	de
		dec	de
		ret
; ---------------------------------------------------------------------------

cfF9_Return:				; DATA XREF: RAM:cfPtrTableo
		push	ix
		pop	hl
		ld	c, (ix+9)
		ld	b, 0
		add	hl, bc
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	(ix+9)
		inc	(ix+9)
		ret
; ---------------------------------------------------------------------------

cfFA_TickMult:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+2),	a
		ret
; ---------------------------------------------------------------------------

cfFB_ChgTransp:				; DATA XREF: RAM:cfPtrTableo
		add	a, (ix+5)
		ld	(ix+5),	a
		ret
; ---------------------------------------------------------------------------

cfFC_PitchSlide:			; DATA XREF: RAM:cfPtrTableo
		cp	1
		jr	nz, loc_CBD
		set	5, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_CBD:				; CODE XREF: RAM:0CB6j
		res	1, (ix+0)
		res	5, (ix+0)
		xor	a
		ld	(ix+10h), a
		ret
; ---------------------------------------------------------------------------

cfFD_RawFrqMode:			; DATA XREF: RAM:cfPtrTableo
		cp	1
		jr	nz, loc_CD3
		set	3, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_CD3:				; CODE XREF: RAM:0CCCj
		res	3, (ix+0)
		ret
; ---------------------------------------------------------------------------

cfFE_SpcFM3Mode:			; DATA XREF: RAM:cfPtrTableo
		ld	a, (ix+1)
		cp	2
		jr	nz, SpcFM3_skip
		set	0, (ix+0)
		ex	de, hl
		call	GetFM3FreqPtr
		ld	b, 4

loc_CE9:				; CODE XREF: RAM:0CFBj
		push	bc
		ld	a, (hl)
		inc	hl
		push	hl
		ld	hl, FM3_FreqVals
		add	a, a
		ld	c, a
		ld	b, 0
		add	hl, bc
		ldi
		ldi
		pop	hl
		pop	bc
		djnz	loc_CE9
		ex	de, hl
		dec	de
		ld	a, 4Fh

; =============== S U B	R O U T	I N E =======================================


SendFM3SpcMode:				; CODE XREF: PlaySoundID:loc_BFAp
		ld	(byte_1C12), a
		ld	c, a
		ld	a, 27h
		call	WriteFMI
		ret
; End of function SendFM3SpcMode

; ---------------------------------------------------------------------------

SpcFM3_skip:				; CODE XREF: RAM:0CDDj
		inc	de
		inc	de
		inc	de
		ret
; ---------------------------------------------------------------------------
FM3_FreqVals:	dw 0, 132h, 18Eh, 1E4h,	234h, 27Eh, 2C2h, 2F0h ; DATA XREF: RAM:0CEDo
; ---------------------------------------------------------------------------

cfMetaCoordFlag:			; DATA XREF: RAM:cfPtrTableo
		ld	hl, cfMetaPtrTable
		rst	ReadPtrTable
		inc	de
		ld	a, (de)
		jp	(hl)
; ---------------------------------------------------------------------------

cf00_SetTempo:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C14), a
		ld	(byte_1C13), a
		ret
; ---------------------------------------------------------------------------

cf01_PlaySnd:				; DATA XREF: RAM:cfMetaPtrTableo
		push	ix
		call	PlaySnd_JumpIn
		pop	ix
		ret
; ---------------------------------------------------------------------------

cf02_MusPause:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C11), a
		or	a
		jr	z, loc_D58
		push	ix
		push	de
		ld	ix, byte_1C40
		ld	b, 0Ah
		ld	de, 30h

loc_D47:				; CODE XREF: RAM:0D50j
		res	7, (ix+0)
		call	SendNoteOff
		add	ix, de
		djnz	loc_D47
		pop	de
		pop	ix
		jp	SilencePSG
; ---------------------------------------------------------------------------

loc_D58:				; CODE XREF: RAM:0D39j
		push	ix
		push	de
		ld	ix, byte_1C40
		ld	b, 0Ah
		ld	de, 30h

loc_D64:				; CODE XREF: RAM:0D6Aj
		set	7, (ix+0)
		add	ix, de
		djnz	loc_D64
		pop	de
		pop	ix
		ret
; ---------------------------------------------------------------------------

cf03_CopyMem:				; DATA XREF: RAM:cfMetaPtrTableo
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	c, (hl)
		ld	b, 0
		inc	hl
		ex	de, hl
		ldir
		dec	de
		ret
; ---------------------------------------------------------------------------

cf04_TickMulAll:			; DATA XREF: RAM:cfMetaPtrTableo
		ld	b, 0Ah
		ld	hl, unk_1C42

loc_D83:				; CODE XREF: RAM:0D8Aj
		push	bc
		ld	bc, 30h
		ld	(hl), a
		add	hl, bc
		pop	bc
		djnz	loc_D83
		ret
; ---------------------------------------------------------------------------

cf05_SSGEG:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(ix+18h), 80h
		ld	(ix+19h), e
		ld	(ix+1Ah), d

; =============== S U B	R O U T	I N E =======================================


SendSSGEG:				; CODE XREF: PlaySoundID:loc_C1Dp
		ld	hl, SSGEG_Ops
		ld	b, 4

loc_D9C:				; CODE XREF: SendSSGEG+Dj
		ld	a, (de)
		inc	de
		ld	c, a
		ld	a, (hl)
		inc	hl
		call	WriteFMIorII
		djnz	loc_D9C
		dec	de
		ret
; End of function SendSSGEG

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

UpdatePSGTrk:				; CODE XREF: UpdateTrack+4j
					; DATA XREF: RAM:cfMetaPtrTableo
		call	TrackTimeout
		jr	nz, loc_DBA
		call	TrkUpdate_Proc
		bit	4, (ix+0)
		ret	nz
		call	PrepareModulat
		jr	loc_DC6
; ---------------------------------------------------------------------------

loc_DBA:				; CODE XREF: UpdateTrack+C48j
		ld	a, (ix+1Eh)
		or	a
		jr	z, loc_DC6
		dec	(ix+1Eh)
		jp	z, SetRest

loc_DC6:				; CODE XREF: UpdateTrack+C55j
					; UpdateTrack+C5Bj
		call	DoPitchSlide
		call	DoModulation
		bit	2, (ix+0)
		ret	nz
		ld	c, (ix+1)
		ld	a, l
		and	0Fh
		or	c
		call	WritePSG
		ld	a, l
		and	0F0h
		or	h
		rrca
		rrca
		rrca
		rrca
		call	WritePSG
		ld	a, (ix+8)
		or	a
		ld	c, 0
		jr	z, loc_DF7
		dec	a
		ld	c, 0Ah
		rst	GetListOfs	; get List 5 (PSG envelopes)
		rst	ReadPtrTable
		call	DoPSGVolEnv
		ld	c, a

loc_DF7:				; CODE XREF: UpdateTrack+C89j
		bit	4, (ix+0)
		ret	nz
		ld	a, (ix+6)
		add	a, c
		bit	4, a
		jr	z, loc_E06
		ld	a, 0Fh

loc_E06:				; CODE XREF: UpdateTrack+C9Fj
		or	(ix+1)
		add	a, 10h
		bit	0, (ix+0)
		jr	nz, loc_E15
		call	WritePSG
		ret
; ---------------------------------------------------------------------------

loc_E15:				; CODE XREF: UpdateTrack+CACj
		add	a, 20h
		call	WritePSG
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR DoPSGVolEnv

loc_E1B:				; CODE XREF: DoPSGVolEnv+1Bj
					; DoPSGVolEnv+26j
		ld	(ix+17h), a
; END OF FUNCTION CHUNK	FOR DoPSGVolEnv

; =============== S U B	R O U T	I N E =======================================


DoPSGVolEnv:				; CODE XREF: UpdateTrack+C90p

; FUNCTION CHUNK AT 0E1B SIZE 00000003 BYTES

		push	hl
		ld	c, (ix+17h)
		ld	b, 0
		add	hl, bc
		ld	a, (hl)
		pop	hl
		bit	7, a
		jr	z, VolEnv_Next
		cp	83h
		jr	z, VolEnv_Off
		cp	81h
		jr	z, VolEnv_Hold
		cp	80h
		jr	z, VolEnv_Reset
		inc	bc
		ld	a, (bc)
		jr	loc_E1B
; ---------------------------------------------------------------------------

VolEnv_Off:				; CODE XREF: DoPSGVolEnv+Fj
		set	4, (ix+0)
		pop	hl
		jp	SetRest
; ---------------------------------------------------------------------------

VolEnv_Reset:				; CODE XREF: DoPSGVolEnv+17j
		xor	a
		jr	loc_E1B
; ---------------------------------------------------------------------------

VolEnv_Hold:				; CODE XREF: DoPSGVolEnv+13j
		pop	hl
		set	4, (ix+0)
		ret
; ---------------------------------------------------------------------------

VolEnv_Next:				; CODE XREF: DoPSGVolEnv+Bj
		inc	(ix+17h)
		ret
; End of function DoPSGVolEnv


; =============== S U B	R O U T	I N E =======================================


SetRest:				; CODE XREF: TrkUpdate_Proc+2Ap
					; UpdateTrack+C60j ...
		set	4, (ix+0)
		bit	2, (ix+0)
		ret	nz
; End of function SetRest


; =============== S U B	R O U T	I N E =======================================


SilencePSGChn:				; CODE XREF: GetSFXChnPtrs+Ep
		ld	a, 1Fh
		add	a, (ix+1)
		or	a
		ret	p
		call	WritePSG
		bit	0, (ix+0)
		ret	z
		ld	a, 0FFh
		call	WritePSG
		ret
; End of function SilencePSGChn


; =============== S U B	R O U T	I N E =======================================


WritePSG:				; CODE XREF: GetSFXChnPtrs+13p
					; SilencePSG:loc_7CCp ...
		push	hl
		push	bc
		push	af
		ld	a, (byte_1C08)
		or	82h
		ld	(byte_1C08), a
	;	ld	hl, 6000h
	;	xor	a
	;	ld	(hl), a
	;	ld	(hl), a
	;	ld	(hl), a
	;	ld	(hl), a
	;	ld	(hl), a
	;	ld	(hl), a
	;	ld	(hl), 1
	;	ld	(hl), a
	;	ld	(hl), 1
		ld	a, (byte_1C08)
		and	7Dh
		ld	(byte_1C08), a
		pop	af
		ld	(7F11h), a
		push	af
		ld	a, (byte_1C08)
		or	82h
		ld	(byte_1C08), a
	;	ld	bc, unk_1C07
	;	ld	hl, 6000h
	;	ld	a, (bc)
	;	rlca
	;	ld	(hl), a
	;	dec	bc
	;	ld	a, (bc)
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
	;	rrca
	;	ld	(hl), a
		ld	a, (byte_1C08)
		and	7Dh
		ld	(byte_1C08), a
		pop	af
		pop	bc
		pop	hl
		ret
; End of function WritePSG

; ---------------------------------------------------------------------------

MainLoop:				; CODE XREF: RAM:00E5j	RAM:0F4Aj ...
		di
		ld	a, 2Bh
		ld	c, 0
		call	WriteFMI

loc_ECB:				; CODE XREF: RAM:0ED0j
		ei
		ld	a, (byte_1C3C)
		or	a
		jr	z, loc_ECB
		di
		ld	a, 2Bh
		ld	c, 80h
		call	WriteFMI
		ei
		ld	hl, DPCMData
		push	hl
		pop	iy
		ld	hl, byte_1C3C
		ld	a, (hl)
		dec	a
		set	7, (hl)
		ld	hl, 8000h
		rst	ReadPtrTable
		ld	c, 80h
		ld	a, (hl)		; get DAC Rate
		inc	hl
		bit	7, a		; The high bit marks the sound as to be	played backwards.
		jp	nz, DACPlayRev
		and	7Fh
		ld	(loc_F18+1), a
		ld	(loc_F2F+1), a
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a

DACLoop:				; CODE XREF: RAM:0F51j
		di
		ld	a, (hl)
		ld	b, a
		and	0Fh
		ld	(loc_F3C+2), a
		ld	a, b
		rlca
		rlca
		rlca
		rlca
		and	0Fh
		ld	(loc_F25+2), a
		ei

loc_F18:				; DATA XREF: RAM:0EF7w
		ld	b, 0Ah

loc_F1A:				; CODE XREF: RAM:loc_F1Aj
		djnz	$
		di
		ld	a, 2Ah
		ld	(4000h), a
		nop
		nop
		ld	a, c

loc_F25:				; DATA XREF: RAM:0F14w
		add	a, (iy+0)
		ld	(4001h), a
		nop
		nop
		ei
		ld	c, a

loc_F2F:				; DATA XREF: RAM:0EFAw
		ld	b, 0Ah

loc_F31:				; CODE XREF: RAM:loc_F31j
		djnz	$
		di
		ld	a, 2Ah
		ld	(4000h), a
		nop
		nop
		ld	a, c

loc_F3C:				; DATA XREF: RAM:0F0Aw
		add	a, (iy+0)
		ld	(4001h), a
		nop
		nop
		ei
		ld	c, a
		ld	a, (byte_1C3C)
		or	a
		jp	p, MainLoop
		inc	hl
		dec	de
		ld	a, d
		or	e
		jp	nz, DACLoop

loc_F54:				; CODE XREF: RAM:0FCDj
		xor	a
		ld	(byte_1C3C), a
		ld	a, (byte_1C08)
		and	0E7h
		ld	(byte_1C08), a
		di
		ld	a, 0B4h
		ld	a, (byte_1D6A)
		call	WriteFMIorII
		ei

loc_F6A:				; CODE XREF: RAM:0FC3j
		jp	MainLoop
; ---------------------------------------------------------------------------

DACPlayRev:				; CODE XREF: RAM:0EF2j
		and	7Fh
		ld	(loc_F91+1), a
		ld	(loc_FA8+1), a
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		add	hl, de

DACLoopRev:				; CODE XREF: RAM:0FCAj
		di
		ld	a, (hl)
		ld	b, a
		and	0Fh
		ld	(loc_F9E+2), a
		ld	a, b
		rlca
		rlca
		rlca
		rlca
		and	0Fh
		ld	(loc_FB5+2), a
		ei

loc_F91:				; DATA XREF: RAM:0F6Fw
		ld	b, 0Ah

loc_F93:				; CODE XREF: RAM:loc_F93j
		djnz	$
		di
		ld	a, 2Ah
		ld	(4000h), a
		nop
		nop
		ld	a, c

loc_F9E:				; DATA XREF: RAM:0F83w
		sub	(iy+0)
		ld	(4001h), a
		nop
		nop
		ei
		ld	c, a

loc_FA8:				; DATA XREF: RAM:0F72w
		ld	b, 0Ah

loc_FAA:				; CODE XREF: RAM:loc_FAAj
		djnz	$
		di
		ld	a, 2Ah
		ld	(4000h), a
		nop
		nop
		ld	a, c

loc_FB5:				; DATA XREF: RAM:0F8Dw
		sub	(iy+0)
		ld	(4001h), a
		nop
		nop
		ei
		ld	c, a
		ld	a, (byte_1C3C)
		or	a
		jp	p, loc_F6A
		dec	hl
		dec	de
		ld	a, d
		or	e
		jp	nz, DACLoopRev
		jp	loc_F54
; ---------------------------------------------------------------------------
DPCMData:	db    0,   1,	2,   4,	  8, 10h, 20h, 40h ; DATA XREF:	RAM:0EDBo
		db  80h,0FFh,0FEh,0FCh,0F8h,0F0h,0E0h,0C0h
		dsb 197h, 0AAh
GeneralPtrList:	dw SndPriorities
		dw 1112h		; actually SpcSFXPtrs
		dw MusicPtrs
		dw SFXPtrs
		dw ModEnvPtrs
		dw VolEnvPtrs
		dw 0A0h			; Song Limit
ModEnvPtrs:	dw VolEnvPtrs
VolEnvPtrs:	dw byte_113C

byte_113C:	db 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3
		db 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5
		db 5, 5, 5, 5, 5, 6, 81h

SndPriorities:	db 80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h, 80h
		db 80h, 80h, 80h, 80h, 7Fh

MusicPtrs:	dw Mus_Menu
SFXptrs:	dw SFX_Select, SFX_Move

Mus_Menu:	incbin "dat/z80/menu.smps.bin"
SFX_Select:	incbin "dat/z80/select.smps.bin"
SFX_Move:	incbin "dat/z80/move.smps.bin"

		dsb 3B6h, 0AAh
DACBankTbl:	dsb 82h, 0AAh
word_1C02:	dw GeneralPtrList		; DATA XREF: GetListOfsr
word_1C04:	dw 0			; DATA XREF: RAM:0A53w	RAM:0084o ...
		db  0	; —
unk_1C07:	db    0			; DATA XREF: RAM:004Ao	WritePSG+2Fo
byte_1C08:	db 0			; DATA XREF: RAM:0042r	RAM:0047w ...

byte_1C09 =	1C09h				; StopAllSound-1FCw ...
unk_1C0A =	1C0Ah
byte_1C0D =	1C0Dh
byte_1C0E =	1C0Eh
byte_1C0F =	1C0Fh
unk_1C10 =	1C10h
byte_1C11 =	1C11h
byte_1C12 =	1C12h
byte_1C13 =	1C13h
byte_1C14 =	1C14h
byte_1C15 =	1C15h
byte_1C16 =	1C16h
byte_1C17 =	1C17h
byte_1C18 =	1C18h
byte_1C19 =	1C19h
unk_1C1A =	1C1Ah
unk_1C22 =	1C22h
unk_1C2A =	1C2Ah
byte_1C32 =	1C32h
word_1C33 =	1C33h
word_1C35 =	1C35h
word_1C37 =	1C37h
word_1C39 =	1C39h
byte_1C3B =	1C3Bh
byte_1C3C =	1C3Ch
byte_1C40 =	1C40h
unk_1C42 =	1C42h
unk_1C4B =	1C4Bh
unk_1C70 =	1C70h
byte_1D60 =	1D60h
unk_1D65 =	1D65h
byte_1D66 =	1D66h
byte_1D68 =	1D68h
byte_1D6A =	1D6Ah
byte_1D90 =	1D90h
byte_1DC0 =	1DC0h
byte_1DF0 =	1DF0h
unk_1E20 =	1E20h
unk_1F70 = 	1F70h
		end
